project_id = "iifgitjximorgvoeruar"

[functions.analyze-food]
verify_jwt = false

[functions.analyze-physique]
verify_jwt = false

[functions.ai-coaching]
verify_jwt = false

[functions.chat]
verify_jwt = false
