import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";

export interface AIWeeklyReport {
  weekStart: string;
  weekEnd: string;
  stats: {
    totalSessions: number;
    totalSets: number;
    totalVolume: number;       // kg lifted total
    avgVolumePerSession: number;
    muscleGroupsHit: string[];
    bestExercise: string | null;
    bestVolume: number;
  };
  aiSummary: string;           // Generated by Claude
  loading: boolean;
  error: string | null;
}

const CACHE_KEY = (userId: string) => `liftmate_ai_weekly_report_${userId}`;
const TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

interface CacheEntry {
  weekStart: string;
  report: Omit<AIWeeklyReport, "loading" | "error">;
  timestamp: number;
}

function getLastWeekDates() {
  const now = new Date();
  const dow = now.getDay();
  const mondayOffset = dow === 0 ? -6 : 1 - dow;

  const thisMonday = new Date(now);
  thisMonday.setDate(now.getDate() + mondayOffset);
  thisMonday.setHours(0, 0, 0, 0);

  const lastMonday = new Date(thisMonday);
  lastMonday.setDate(thisMonday.getDate() - 7);

  const lastSunday = new Date(thisMonday);
  lastSunday.setDate(thisMonday.getDate() - 1);
  lastSunday.setHours(23, 59, 59, 999);

  return {
    start: lastMonday.toISOString().split("T")[0],
    end: lastSunday.toISOString().split("T")[0],
  };
}

function isMonday(): boolean {
  return new Date().getDay() === 1;
}

export function useAIWeeklyReport(): AIWeeklyReport {
  const { user } = useAuth();
  const [state, setState] = useState<Omit<AIWeeklyReport, "loading" | "error">>({
    weekStart: "",
    weekEnd: "",
    stats: { totalSessions: 0, totalSets: 0, totalVolume: 0, avgVolumePerSession: 0, muscleGroupsHit: [], bestExercise: null, bestVolume: 0 },
    aiSummary: "",
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [triggered, setTriggered] = useState(false);

  // Expose a way to trigger generation even outside Monday (for testing / manual refresh)
  useEffect(() => {
    if (!user || triggered) return;
    const { start } = getLastWeekDates();

    // Try cache first — reject if aiSummary looks like raw JSON (legacy streaming bug)
    try {
      const raw = localStorage.getItem(CACHE_KEY(user.id));
      if (raw) {
        const cache: CacheEntry = JSON.parse(raw);
        const expired = Date.now() - cache.timestamp > TTL_MS;
        const summary = cache.report?.aiSummary ?? "";
        const isCorrupted = summary.includes("{") || summary.includes("chatcmpl") || summary.includes('"type"');
        if (!expired && cache.weekStart === start && !isCorrupted) {
          setState(cache.report);
          setTriggered(true);
          return;
        }
        // Corrupted or stale — purge and regenerate
        if (isCorrupted) localStorage.removeItem(CACHE_KEY(user.id));
      }
    } catch { /* ignore */ }

    // Only auto-generate on Mondays (or if forced externally)
    if (!isMonday()) return;

    setTriggered(true);
    generate(user.id);
  }, [user]);

  const generate = async (userId: string) => {
    setLoading(true);
    setError(null);

    const { start, end } = getLastWeekDates();

    try {
      // 1. Fetch sessions from last week
      const { data: sessions } = await supabase
        .from("workout_sessions")
        .select("id, date, muscle_groups, performance_score")
        .eq("user_id", userId)
        .eq("status", "completed")
        .gte("date", start)
        .lte("date", end)
        .order("date", { ascending: true });

      const sessionList = sessions || [];
      const sessionIds = sessionList.map((s) => s.id);

      // 2. Fetch sets for those sessions
      const { data: sets } = sessionIds.length > 0
        ? await supabase
            .from("workout_sets")
            .select("session_id, exercise_id, weight, reps")
            .in("session_id", sessionIds)
            .eq("set_type", "working")
        : { data: [] };

      const setList = sets || [];

      // 3. Fetch exercise names
      const exerciseIds = [...new Set(setList.map((s) => s.exercise_id).filter(Boolean))];
      const { data: exercises } = exerciseIds.length > 0
        ? await supabase.from("exercises").select("id, name").in("id", exerciseIds)
        : { data: [] };

      const exMap: Record<string, string> = {};
      for (const ex of exercises || []) exMap[ex.id] = ex.name;

      // 4. Compute stats
      const totalVolume = setList.reduce((s, r) => s + Number(r.weight) * r.reps, 0);
      const totalSets   = setList.length;
      const muscleGroupsHit = [...new Set(sessionList.flatMap((s) => Array.isArray(s.muscle_groups) ? s.muscle_groups : []))];

      // Best exercise by volume
      const volByExercise: Record<string, number> = {};
      for (const r of setList) {
        if (!r.exercise_id) continue;
        const name = exMap[r.exercise_id] || "Exercício";
        volByExercise[name] = (volByExercise[name] ?? 0) + Number(r.weight) * r.reps;
      }
      const bestEntry = Object.entries(volByExercise).sort((a, b) => b[1] - a[1])[0];

      const stats = {
        totalSessions: sessionList.length,
        totalSets,
        totalVolume: Math.round(totalVolume),
        avgVolumePerSession: sessionList.length > 0 ? Math.round(totalVolume / sessionList.length) : 0,
        muscleGroupsHit,
        bestExercise: bestEntry?.[0] ?? null,
        bestVolume: Math.round(bestEntry?.[1] ?? 0),
      };

      // 5. Generate AI summary via edge function
      let aiSummary = "";

      if (stats.totalSessions > 0) {
        const prompt = `Sou o Coach IA do LiftMate. Gera um resumo motivacional e objetivo da semana passada do utilizador (máximo 3 frases, em português de Portugal):

Dados da semana (${start} a ${end}):
- Sessões completadas: ${stats.totalSessions}
- Volume total: ${(stats.totalVolume / 1000).toFixed(1)} toneladas
- Séries totais: ${stats.totalSets}
- Grupos musculares: ${stats.muscleGroupsHit.join(", ") || "—"}
${stats.bestExercise ? `- Melhor exercício: ${stats.bestExercise} (${(stats.bestVolume / 1000).toFixed(1)}t)` : ""}

Escreve 2-3 frases curtas: 1 frase de balanço, 1 frase de destaque positivo, 1 sugestão para esta semana. Sem asteriscos, sem markdown.`;

        try {
          const { data: { session } } = await supabase.auth.getSession();
          const authHeaders: Record<string, string> = {};
          if (session?.access_token) {
            authHeaders["Authorization"] = `Bearer ${session.access_token}`;
          }

          const response = await fetch(
            `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/chat`,
            {
              method: "POST",
              headers: { "Content-Type": "application/json", ...authHeaders },
              body: JSON.stringify({
                messages: [{ role: "user", content: prompt }],
                context: "",
                stream: false,
              }),
            }
          );

          if (response.ok) {
            const data = await response.json();
            aiSummary =
              data.content?.[0]?.text?.trim() ||
              data.choices?.[0]?.message?.content?.trim() ||
              "";
          }
        } catch (aiErr) {
          console.warn("[AIWeeklyReport] AI generation failed, using fallback", aiErr);
          aiSummary = `Completaste ${stats.totalSessions} treino${stats.totalSessions !== 1 ? "s" : ""} na semana passada com ${(stats.totalVolume / 1000).toFixed(1)}t de volume total. ${stats.muscleGroupsHit.length > 0 ? `Trabalhaste: ${stats.muscleGroupsHit.slice(0, 3).join(", ")}.` : ""} Continua assim esta semana!`;
        }
      } else {
        aiSummary = "Não houve treinos registados na semana passada. Esta semana é a tua oportunidade — começa com o primeiro treino!";
      }

      const report = { weekStart: start, weekEnd: end, stats, aiSummary };

      // Cache
      const cache: CacheEntry = { weekStart: start, report, timestamp: Date.now() };
      localStorage.setItem(CACHE_KEY(userId), JSON.stringify(cache));

      setState(report);
    } catch (err) {
      console.error("[AIWeeklyReport] Error:", err);
      setError("Não foi possível gerar o relatório.");
    } finally {
      setLoading(false);
    }
  };

  // Expose manual trigger for non-Monday testing
  const forceGenerate = () => {
    if (user) { setTriggered(true); generate(user.id); }
  };

  return { ...state, loading, error };
}

// Helper to check if report card should be shown
export function shouldShowWeeklyReport(userId: string): boolean {
  if (isMonday()) return true;
  try {
    const raw = localStorage.getItem(CACHE_KEY(userId));
    if (!raw) return false;
    const cache: CacheEntry = JSON.parse(raw);
    const expired = Date.now() - cache.timestamp > TTL_MS;
    const { start } = getLastWeekDates();
    return !expired && cache.weekStart === start && cache.report.aiSummary !== "";
  } catch {
    return false;
  }
}
