import { useState, createContext, useContext, useEffect } from "react";

export type Language = 
  | "pt-PT" 
  | "pt-BR" 
  | "en" 
  | "es" 
  | "fr" 
  | "de" 
  | "it" 
  | "nl" 
  | "ru" 
  | "zh" 
  | "ja" 
  | "ko";

export interface LanguageOption {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: LanguageOption[] = [
  { code: "pt-PT", name: "Portuguese (Portugal)", nativeName: "Português (Portugal)", flag: "🇵🇹" },
  { code: "pt-BR", name: "Portuguese (Brazil)", nativeName: "Português (Brasil)", flag: "🇧🇷" },
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
];

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getLanguageOption: (code: Language) => LanguageOption | undefined;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const useLanguage = () => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem("liftmate_language");
      return (saved as Language) || "pt-PT";
    }
    return "pt-PT";
  });

  useEffect(() => {
    localStorage.setItem("liftmate_language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string) => {
    const translations = getTranslations(language);
    return translations[key] || key;
  };

  const getLanguageOption = (code: Language) => {
    return languages.find(l => l.code === code);
  };

  return { language, setLanguage, t, getLanguageOption };
};

// Complete translations object
const translations: Record<Language, Record<string, string>> = {
  "pt-PT": {
    // Auth
    "auth.welcomeTo": "Bem-vindo ao",
    "auth.journeyStarts": "A tua jornada de treino começa aqui.",
    "auth.createAccount": "Criar Conta",
    "auth.login": "Entrar",
    "auth.yourName": "O teu nome",
    "auth.email": "Email",
    "auth.password": "Palavra-passe",
    "auth.noAccount": "Não tens conta?",
    "auth.hasAccount": "Já tens conta?",
    "auth.signUp": "Criar Conta",
    "auth.back": "Voltar",
    "auth.termsOfUse": "Termos de Uso",
    "auth.privacyPolicy": "Política de Privacidade",
    "auth.loginSuccess": "Login efetuado com sucesso!",
    "auth.accountCreated": "Conta criada com sucesso!",
    "auth.emailRegistered": "Este email já está registado. Tenta fazer login.",
    "auth.invalidCredentials": "Email ou password incorretos.",
    
    // Home
    "home.rest": "Descanso",
    "home.todayWorkout": "Treino de hoje",
    "home.recoveryDay": "Dia de recuperação",
    "home.progress": "Progresso",
    "home.seriesDone": "Séries feitas",
    "home.totalReps": "Reps totais",
    "home.trainingMin": "Min treino",
    "home.suggestedExercise": "Exercício sugerido",
    "home.focusOn": "Foco em",
    "home.recovery": "Recuperação",
    "home.upcomingWorkouts": "Próximos treinos",
    "home.workoutComplete": "Treino completo! 💪",
    "home.congratsAllExercises": "Parabéns, completaste todos os exercícios de hoje!",
    "home.exercises": "Exercícios",
    "home.suggestedExercisesFor": "Exercícios sugeridos para",
    "home.resetOnboarding": "Refazer onboarding",
    "home.resetOnboardingDesc": "Redefine as tuas preferências de treino",
    "home.settings": "Configurações",
    
    // Workout
    "workout.restDay": "Dia de Descanso",
    "workout.activeRecovery": "Recuperação Ativa",
    "workout.restImportant": "O descanso é tão importante quanto o treino. Aproveita para recuperar!",
    "workout.trainingType": "Tipo de Treino",
    "workout.strength": "Força",
    "workout.hypertrophy": "Hipertrofia",
    "workout.endurance": "Resistência",
    "workout.savedExercisesToday": "Exercícios Guardados Hoje",
    "workout.restCalculation": "Cálculo do Descanso",
    "workout.baseTime": "Tempo base",
    "workout.weight": "Peso",
    "workout.reps": "Repetições",
    "workout.highSets": "Séries altas",
    "workout.totalRecommended": "Total recomendado",
    "workout.restTimer": "Temporizador",
    "workout.restEnded": "Tempo de descanso terminado! 💪",
    "workout.selectExercise": "Seleciona um exercício primeiro",
    "workout.saved": "guardado!",
    
    // Nutrition
    "nutrition.title": "Nutrição",
    "nutrition.mealsToday": "Refeições de Hoje",
    "nutrition.noMeals": "Ainda não registaste nenhuma refeição",
    "nutrition.useScannerHint": "Usa o scanner IA acima para começar!",
    "nutrition.protein": "Proteína",
    "nutrition.carbs": "Carbs",
    "nutrition.fat": "Gordura",
    "nutrition.plansRecipes": "Planos & Receitas",
    "nutrition.tipsForAthletes": "Dicas para Atletas",
    "nutrition.postWorkout": "Pós-treino",
    "nutrition.postWorkoutTip": "Proteína + carbs até 2h após treino",
    "nutrition.distributedProtein": "Proteína distribuída",
    "nutrition.distributedProteinTip": "20-40g por refeição é ideal",
    
    // Chat
    "chat.hello": "Olá! Sou o",
    "chat.askMe": "Pergunta-me sobre treinos, nutrição, recuperação ou o teu progresso!",
    "chat.suggestWorkout": "Sugere treino",
    "chat.recovery": "Recuperação",
    "chat.substitute": "Substituir",
    "chat.progressLabel": "Progresso",
    "chat.nutritionLabel": "Nutrição",
    "chat.restLabel": "Descanso",
    "chat.continuousMode": "Conversa contínua",
    "chat.continuousModeOn": "Modo contínuo ativado",
    "chat.continuousModeOff": "Modo contínuo desativado",
    "chat.listen": "Ouvir",
    "chat.playing": "A reproduzir...",
    "chat.recording": "A gravar...",
    "chat.tapToCancel": "Toca para cancelar",
    "chat.errorCreatingConversation": "Erro ao criar conversa. Faz login para guardar o histórico.",
    "chat.errorAI": "Erro ao comunicar com a IA. Tenta novamente.",
    "chat.limitExceeded": "Limite de pedidos excedido. Tenta novamente em alguns segundos.",
    "chat.creditsExhausted": "Créditos esgotados. Adiciona mais créditos na área de definições.",
    
    // Alerts
    "alerts.title": "Alertas",
    "alerts.subtitle": "O teu assistente de treino",
    "alerts.workoutRecorded": "Treino registado! 💪",
    "alerts.streakMilestone": "Streak Milestone!",
    "alerts.consecutiveDays": "dias consecutivos de treino!",
    
    // Settings
    "settings.title": "Definições",
    "settings.subtitle": "Personaliza o teu treino",
    "settings.aiName": "Nome do assistente",
    "settings.calendar": "Calendário",
    "settings.tapToEdit": "Toca para editar",
    "settings.subscription": "Subscrição",
    "settings.managePayment": "Gerir plano e pagamento",
    "settings.manage": "Gerir",
    "settings.theme": "Tema",
    "settings.changeAppearance": "Altera a aparência",
    "settings.language": "Idioma",
    "settings.selectLanguage": "Seleciona o idioma",
    "settings.termsOfUse": "Termos de Uso",
    "settings.privacyPolicy": "Política de Privacidade",
    "settings.support": "Suporte",
    "settings.logout": "Terminar sessão",
    "settings.logoutDesc": "Sair da conta",
    "settings.lightTheme": "Tema claro ativado",
    "settings.darkTheme": "Tema escuro ativado",
    "settings.languageUpdated": "Idioma atualizado!",
    "settings.aiNameUpdated": "Nome da IA atualizado!",
    "settings.errorPortal": "Erro ao abrir portal de gestão",
    "settings.sessionEnded": "Sessão terminada",
    "settings.errorLogout": "Erro ao terminar sessão",
    
    // BottomNav
    "nav.home": "Início",
    "nav.workout": "Treino",
    "nav.nutrition": "Nutrição",
    "nav.chat": "Chat",
    "nav.alerts": "Alertas",
    
    // Common
    "common.training": "Treino",
    "common.rest": "Descanso",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.back": "Voltar",
    "common.loading": "A carregar...",
    "common.error": "Erro",
    "common.success": "Sucesso",
    "common.incredible": "Incrível!",
    
    // Days
    "days.sunday": "Domingo",
    "days.monday": "Segunda-feira",
    "days.tuesday": "Terça-feira",
    "days.wednesday": "Quarta-feira",
    "days.thursday": "Quinta-feira",
    "days.friday": "Sexta-feira",
    "days.saturday": "Sábado",
    "days.sun": "Dom",
    "days.mon": "Seg",
    "days.tue": "Ter",
    "days.wed": "Qua",
    "days.thu": "Qui",
    "days.fri": "Sex",
    "days.sat": "Sáb",
    
    // AI Workout Generator
    "aiWorkout.title": "Gerador de Treino IA",
    "aiWorkout.generating": "A gerar treino personalizado...",
    "aiWorkout.generateFor": "Gerar Treino para",
    "aiWorkout.noMuscleGroups": "Não há grupos musculares definidos para hoje",
    "aiWorkout.success": "Treino gerado com sucesso! 💪",
    "aiWorkout.error": "Erro ao gerar treino. Tenta novamente.",
    "aiWorkout.progress": "Progresso",
    "aiWorkout.exercises": "exercícios",
    "aiWorkout.duration": "Duração",
    "aiWorkout.level": "Nível",
    "aiWorkout.warmup": "Aquecimento",
    "aiWorkout.cooldown": "Cooldown",
    "aiWorkout.tip": "Dica",
    "aiWorkout.equipment": "Equipamento",
    "aiWorkout.useInRecord": "Usar no registo →",
    "aiWorkout.regenerate": "Gerar Novo Treino",
    "aiWorkout.rest": "descanso",
    
    // Food Scanner
    "foodScanner.addMeal": "Adicionar Refeição",
    "foodScanner.takePhoto": "Tirar Foto",
    "foodScanner.gallery": "Galeria",
    "foodScanner.orDescribe": "ou descreve",
    "foodScanner.exampleDescription": "Ex: 200g frango grelhado, arroz integral...",
    "foodScanner.analyzing": "A analisar com IA...",
    "foodScanner.analysisComplete": "Análise completa!",
    "foodScanner.foodsIdentified": "alimento(s) identificado(s)",
    "foodScanner.analysisError": "Erro na análise",
    "foodScanner.analysisErrorDesc": "Não foi possível analisar a imagem. Tenta novamente.",
    "foodScanner.textAnalysisError": "Não foi possível analisar a descrição.",
    "foodScanner.addedFood": "adicionado",
    "foodScanner.mealAdded": "Refeição adicionada!",
    "foodScanner.kcalRegistered": "kcal registadas",
    "foodScanner.identifiedFoods": "Alimentos identificados",
    "foodScanner.total": "Total",
    "foodScanner.protein": "Proteína",
    "foodScanner.carbs": "Carbs",
    "foodScanner.fat": "Gordura",
    "foodScanner.fiber": "Fibra",
    "foodScanner.aiScanner": "IA Scanner",
    "foodScanner.search": "Pesquisar",
    "foodScanner.searchFoods": "Pesquisar alimentos...",
    "foodScanner.suggestions": "Sugestões",
    "foodScanner.postWorkoutSuggestions": "Pós-Treino",
    "foodScanner.preWorkoutSuggestions": "Pré-Treino",
    "foodScanner.results": "Resultados",
    "foodScanner.noFoodFound": "Nenhum alimento encontrado",
    "foodScanner.selected": "Selecionados",
    "foodScanner.items": "itens",
    "foodScanner.newAnalysis": "Nova Análise",
    "foodScanner.clear": "Limpar",
    "foodScanner.add": "Adicionar",
    "foodScanner.postWorkoutWindow": "Janela Pós-Treino",
    "foodScanner.preWorkoutPrep": "Preparação Pré-Treino",
    "foodScanner.activeRecovery": "Recuperação Ativa",
    
    // Hydration Card
    "hydration.title": "Hidratação",
    "hydration.every": "A cada",
    "hydration.min": "min",
    "hydration.configure": "Configurar Hidratação",
    "hydration.enableReminders": "Ativar lembretes",
    "hydration.interval": "Intervalo",
    "hydration.dailyGoal": "Meta diária",
    "hydration.remove": "Remover",
    
    // Streak Card
    "streak.title": "Consistência",
    "streak.recordedToday": "Treino registado hoje! 💪",
    "streak.startNew": "Começa uma nova sequência!",
    "streak.legendary": "Lendário! Continua assim!",
    "streak.unstoppable": "Imparável! 2 semanas!",
    "streak.oneWeek": "Uma semana! Excelente!",
    "streak.dontBreak": "Não quebres a sequência!",
    "streak.recordWorkout": "Registar Treino",
    "streak.days": "DIAS",
    "streak.record": "Recorde",
    "streak.daysLabel": "dias",
    "streak.total": "Total",
    "streak.workouts": "treinos",
    
    // Supplements Card
    "supplements.title": "Suplementação",
    "supplements.activeReminders": "lembretes ativos",
    "supplements.newSupplement": "Novo Suplemento",
    "supplements.name": "Nome",
    "supplements.namePlaceholder": "Ex: Omega 3, BCAA...",
    "supplements.time": "Horário",
    "supplements.addSupplement": "Adicionar Suplemento",
    "supplements.noSupplements": "Nenhum suplemento configurado",
    
    // Sleep Card
    "sleep.title": "Sono & Recuperação",
    "sleep.reminderBefore": "Lembrete",
    "sleep.minBefore": "min antes",
    "sleep.configure": "Configurar Sono",
    "sleep.enableReminders": "Ativar lembretes",
    "sleep.sleep": "Dormir",
    "sleep.wake": "Acordar",
    "sleep.reminderBeforeLabel": "Lembrete antes",
    "sleep.excellent": "Ótimo",
    "sleep.good": "Bom",
    "sleep.fair": "Razoável",
    "sleep.insufficient": "Insuficiente",
    "sleep.sleepEqualsGains": "Sono = Ganhos",
    "sleep.recoversMusles": "Recupera músculos",
    
    // Quick Timer Card
    "timer.title": "Timer Rápido",
    "timer.restBetweenSets": "Descanso entre séries",
    "timer.remaining": "restantes",
    "timer.stop": "Parar",
    "timer.restart": "Reiniciar",
    
    // Meal Notification Card
    "mealNotification.title": "Lembretes de Refeições",
    "mealNotification.enableNotificationsFirst": "Ativa as notificações primeiro",
    "mealNotification.mealsActive": "refeições ativas",
    "mealNotification.disabled": "Desativado",
    "mealNotification.mealTimes": "Horários das Refeições",
    "mealNotification.breakfast": "Pequeno-Almoço",
    "mealNotification.morningSnack": "Lanche Manhã",
    "mealNotification.lunch": "Almoço",
    "mealNotification.afternoonSnack": "Lanche Tarde",
    "mealNotification.dinner": "Jantar",
    "mealNotification.preWorkout": "Pré-Treino",
    "mealNotification.postWorkout": "Pós-Treino",
    "mealNotification.waterReminders": "Lembretes de Água",
    "mealNotification.hydrationThroughDay": "Hidratação ao longo do dia",
    "mealNotification.start": "Início",
    "mealNotification.end": "Fim",
    "mealNotification.intervalHours": "Intervalo (horas)",
    
    // Workout Reminder Card
    "workoutReminder.title": "Lembrete de Treino",
    "workoutReminder.minBeforeWorkout": "min antes do treino",
    "workoutReminder.configure": "Configurar Lembrete",
    "workoutReminder.enableReminders": "Ativar lembretes",
    "workoutReminder.workoutTime": "Hora do treino",
    "workoutReminder.notifyBefore": "Avisar antes",
    "workoutReminder.motivationalMessage": "Mensagem motivacional",
    "workoutReminder.enableNotificationsFirst": "Ativa as notificações primeiro para usar lembretes",
    "workoutReminder.timeToTrain": "Hora de Treinar!",
    "workoutReminder.now": "agora",
    "workoutReminder.notificationPreview": "Pré-visualização da notificação",
  },
  "pt-BR": {
    // Auth
    "auth.welcomeTo": "Bem-vindo ao",
    "auth.journeyStarts": "Sua jornada de treino começa aqui.",
    "auth.createAccount": "Criar Conta",
    "auth.login": "Entrar",
    "auth.yourName": "Seu nome",
    "auth.email": "Email",
    "auth.password": "Senha",
    "auth.noAccount": "Não tem conta?",
    "auth.hasAccount": "Já tem conta?",
    "auth.signUp": "Criar Conta",
    "auth.back": "Voltar",
    "auth.termsOfUse": "Termos de Uso",
    "auth.privacyPolicy": "Política de Privacidade",
    "auth.loginSuccess": "Login efetuado com sucesso!",
    "auth.accountCreated": "Conta criada com sucesso!",
    "auth.emailRegistered": "Este email já está registrado. Tente fazer login.",
    "auth.invalidCredentials": "Email ou senha incorretos.",
    
    // Home
    "home.rest": "Descanso",
    "home.todayWorkout": "Treino de hoje",
    "home.recoveryDay": "Dia de recuperação",
    "home.progress": "Progresso",
    "home.seriesDone": "Séries feitas",
    "home.totalReps": "Reps totais",
    "home.trainingMin": "Min treino",
    "home.suggestedExercise": "Exercício sugerido",
    "home.focusOn": "Foco em",
    "home.recovery": "Recuperação",
    "home.upcomingWorkouts": "Próximos treinos",
    "home.workoutComplete": "Treino completo! 💪",
    "home.congratsAllExercises": "Parabéns, você completou todos os exercícios de hoje!",
    "home.exercises": "Exercícios",
    "home.suggestedExercisesFor": "Exercícios sugeridos para",
    "home.resetOnboarding": "Refazer onboarding",
    "home.resetOnboardingDesc": "Redefina suas preferências de treino",
    "home.settings": "Configurações",
    
    // Workout
    "workout.restDay": "Dia de Descanso",
    "workout.activeRecovery": "Recuperação Ativa",
    "workout.restImportant": "O descanso é tão importante quanto o treino. Aproveite para recuperar!",
    "workout.trainingType": "Tipo de Treino",
    "workout.strength": "Força",
    "workout.hypertrophy": "Hipertrofia",
    "workout.endurance": "Resistência",
    "workout.savedExercisesToday": "Exercícios Salvos Hoje",
    "workout.restCalculation": "Cálculo do Descanso",
    "workout.baseTime": "Tempo base",
    "workout.weight": "Peso",
    "workout.reps": "Repetições",
    "workout.highSets": "Séries altas",
    "workout.totalRecommended": "Total recomendado",
    "workout.restTimer": "Cronômetro",
    "workout.restEnded": "Tempo de descanso terminado! 💪",
    "workout.selectExercise": "Selecione um exercício primeiro",
    "workout.saved": "salvo!",
    
    // Nutrition
    "nutrition.title": "Nutrição",
    "nutrition.mealsToday": "Refeições de Hoje",
    "nutrition.noMeals": "Você ainda não registrou nenhuma refeição",
    "nutrition.useScannerHint": "Use o scanner IA acima para começar!",
    "nutrition.protein": "Proteína",
    "nutrition.carbs": "Carbs",
    "nutrition.fat": "Gordura",
    "nutrition.plansRecipes": "Planos & Receitas",
    "nutrition.tipsForAthletes": "Dicas para Atletas",
    "nutrition.postWorkout": "Pós-treino",
    "nutrition.postWorkoutTip": "Proteína + carbs até 2h após treino",
    "nutrition.distributedProtein": "Proteína distribuída",
    "nutrition.distributedProteinTip": "20-40g por refeição é ideal",
    
    // Chat
    "chat.hello": "Olá! Sou o",
    "chat.askMe": "Pergunte-me sobre treinos, nutrição, recuperação ou seu progresso!",
    "chat.suggestWorkout": "Sugere treino",
    "chat.recovery": "Recuperação",
    "chat.substitute": "Substituir",
    "chat.progressLabel": "Progresso",
    "chat.nutritionLabel": "Nutrição",
    "chat.restLabel": "Descanso",
    "chat.continuousMode": "Conversa contínua",
    "chat.continuousModeOn": "Modo contínuo ativado",
    "chat.continuousModeOff": "Modo contínuo desativado",
    "chat.listen": "Ouvir",
    "chat.playing": "Reproduzindo...",
    "chat.recording": "Gravando...",
    "chat.tapToCancel": "Toque para cancelar",
    "chat.errorCreatingConversation": "Erro ao criar conversa. Faça login para salvar o histórico.",
    "chat.errorAI": "Erro ao comunicar com a IA. Tente novamente.",
    "chat.limitExceeded": "Limite de pedidos excedido. Tente novamente em alguns segundos.",
    "chat.creditsExhausted": "Créditos esgotados. Adicione mais créditos na área de configurações.",
    
    // Alerts
    "alerts.title": "Alertas",
    "alerts.subtitle": "Seu assistente de treino",
    "alerts.workoutRecorded": "Treino registrado! 💪",
    "alerts.streakMilestone": "Streak Milestone!",
    "alerts.consecutiveDays": "dias consecutivos de treino!",
    
    // Settings
    "settings.title": "Configurações",
    "settings.subtitle": "Personalize seu treino",
    "settings.aiName": "Nome do assistente",
    "settings.calendar": "Calendário",
    "settings.tapToEdit": "Toque para editar",
    "settings.subscription": "Assinatura",
    "settings.managePayment": "Gerenciar plano e pagamento",
    "settings.manage": "Gerenciar",
    "settings.theme": "Tema",
    "settings.changeAppearance": "Alterar aparência",
    "settings.language": "Idioma",
    "settings.selectLanguage": "Selecione o idioma",
    "settings.termsOfUse": "Termos de Uso",
    "settings.privacyPolicy": "Política de Privacidade",
    "settings.support": "Suporte",
    "settings.logout": "Encerrar sessão",
    "settings.logoutDesc": "Sair da conta",
    "settings.lightTheme": "Tema claro ativado",
    "settings.darkTheme": "Tema escuro ativado",
    "settings.languageUpdated": "Idioma atualizado!",
    "settings.aiNameUpdated": "Nome da IA atualizado!",
    "settings.errorPortal": "Erro ao abrir portal de gerenciamento",
    "settings.sessionEnded": "Sessão encerrada",
    "settings.errorLogout": "Erro ao encerrar sessão",
    
    // BottomNav
    "nav.home": "Início",
    "nav.workout": "Treino",
    "nav.nutrition": "Nutrição",
    "nav.chat": "Chat",
    "nav.alerts": "Alertas",
    
    // Common
    "common.training": "Treino",
    "common.rest": "Descanso",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.back": "Voltar",
    "common.loading": "Carregando...",
    "common.error": "Erro",
    "common.success": "Sucesso",
    "common.incredible": "Incrível!",
    
    // Days
    "days.sunday": "Domingo",
    "days.monday": "Segunda-feira",
    "days.tuesday": "Terça-feira",
    "days.wednesday": "Quarta-feira",
    "days.thursday": "Quinta-feira",
    "days.friday": "Sexta-feira",
    "days.saturday": "Sábado",
    "days.sun": "Dom",
    "days.mon": "Seg",
    "days.tue": "Ter",
    "days.wed": "Qua",
    "days.thu": "Qui",
    "days.fri": "Sex",
    "days.sat": "Sáb",
    
    // AI Workout Generator
    "aiWorkout.title": "Gerador de Treino IA",
    "aiWorkout.generating": "Gerando treino personalizado...",
    "aiWorkout.generateFor": "Gerar Treino para",
    "aiWorkout.noMuscleGroups": "Não há grupos musculares definidos para hoje",
    "aiWorkout.success": "Treino gerado com sucesso! 💪",
    "aiWorkout.error": "Erro ao gerar treino. Tente novamente.",
    "aiWorkout.progress": "Progresso",
    "aiWorkout.exercises": "exercícios",
    "aiWorkout.duration": "Duração",
    "aiWorkout.level": "Nível",
    "aiWorkout.warmup": "Aquecimento",
    "aiWorkout.cooldown": "Cooldown",
    "aiWorkout.tip": "Dica",
    "aiWorkout.equipment": "Equipamento",
    "aiWorkout.useInRecord": "Usar no registro →",
    "aiWorkout.regenerate": "Gerar Novo Treino",
    "aiWorkout.rest": "descanso",
    
    // Food Scanner
    "foodScanner.addMeal": "Adicionar Refeição",
    "foodScanner.takePhoto": "Tirar Foto",
    "foodScanner.gallery": "Galeria",
    "foodScanner.orDescribe": "ou descreva",
    "foodScanner.exampleDescription": "Ex: 200g frango grelhado, arroz integral...",
    "foodScanner.analyzing": "Analisando com IA...",
    "foodScanner.analysisComplete": "Análise completa!",
    "foodScanner.foodsIdentified": "alimento(s) identificado(s)",
    "foodScanner.analysisError": "Erro na análise",
    "foodScanner.analysisErrorDesc": "Não foi possível analisar a imagem. Tente novamente.",
    "foodScanner.textAnalysisError": "Não foi possível analisar a descrição.",
    "foodScanner.addedFood": "adicionado",
    "foodScanner.mealAdded": "Refeição adicionada!",
    "foodScanner.kcalRegistered": "kcal registradas",
    "foodScanner.identifiedFoods": "Alimentos identificados",
    "foodScanner.total": "Total",
    "foodScanner.protein": "Proteína",
    "foodScanner.carbs": "Carbs",
    "foodScanner.fat": "Gordura",
    "foodScanner.fiber": "Fibra",
    "foodScanner.aiScanner": "IA Scanner",
    "foodScanner.search": "Pesquisar",
    "foodScanner.searchFoods": "Pesquisar alimentos...",
    "foodScanner.suggestions": "Sugestões",
    "foodScanner.postWorkoutSuggestions": "Pós-Treino",
    "foodScanner.preWorkoutSuggestions": "Pré-Treino",
    "foodScanner.results": "Resultados",
    "foodScanner.noFoodFound": "Nenhum alimento encontrado",
    "foodScanner.selected": "Selecionados",
    "foodScanner.items": "itens",
    "foodScanner.newAnalysis": "Nova Análise",
    "foodScanner.clear": "Limpar",
    "foodScanner.add": "Adicionar",
    "foodScanner.postWorkoutWindow": "Janela Pós-Treino",
    "foodScanner.preWorkoutPrep": "Preparação Pré-Treino",
    "foodScanner.activeRecovery": "Recuperação Ativa",
    
    // Hydration Card
    "hydration.title": "Hidratação",
    "hydration.every": "A cada",
    "hydration.min": "min",
    "hydration.configure": "Configurar Hidratação",
    "hydration.enableReminders": "Ativar lembretes",
    "hydration.interval": "Intervalo",
    "hydration.dailyGoal": "Meta diária",
    "hydration.remove": "Remover",
    
    // Streak Card
    "streak.title": "Consistência",
    "streak.recordedToday": "Treino registrado hoje! 💪",
    "streak.startNew": "Comece uma nova sequência!",
    "streak.legendary": "Lendário! Continue assim!",
    "streak.unstoppable": "Imparável! 2 semanas!",
    "streak.oneWeek": "Uma semana! Excelente!",
    "streak.dontBreak": "Não quebre a sequência!",
    "streak.recordWorkout": "Registrar Treino",
    "streak.days": "DIAS",
    "streak.record": "Recorde",
    "streak.daysLabel": "dias",
    "streak.total": "Total",
    "streak.workouts": "treinos",
    
    // Supplements Card
    "supplements.title": "Suplementação",
    "supplements.activeReminders": "lembretes ativos",
    "supplements.newSupplement": "Novo Suplemento",
    "supplements.name": "Nome",
    "supplements.namePlaceholder": "Ex: Omega 3, BCAA...",
    "supplements.time": "Horário",
    "supplements.addSupplement": "Adicionar Suplemento",
    "supplements.noSupplements": "Nenhum suplemento configurado",
    
    // Sleep Card
    "sleep.title": "Sono & Recuperação",
    "sleep.reminderBefore": "Lembrete",
    "sleep.minBefore": "min antes",
    "sleep.configure": "Configurar Sono",
    "sleep.enableReminders": "Ativar lembretes",
    "sleep.sleep": "Dormir",
    "sleep.wake": "Acordar",
    "sleep.reminderBeforeLabel": "Lembrete antes",
    "sleep.excellent": "Ótimo",
    "sleep.good": "Bom",
    "sleep.fair": "Razoável",
    "sleep.insufficient": "Insuficiente",
    "sleep.sleepEqualsGains": "Sono = Ganhos",
    "sleep.recoversMusles": "Recupera músculos",
    
    // Quick Timer Card
    "timer.title": "Timer Rápido",
    "timer.restBetweenSets": "Descanso entre séries",
    "timer.remaining": "restantes",
    "timer.stop": "Parar",
    "timer.restart": "Reiniciar",
    
    // Meal Notification Card
    "mealNotification.title": "Lembretes de Refeições",
    "mealNotification.enableNotificationsFirst": "Ative as notificações primeiro",
    "mealNotification.mealsActive": "refeições ativas",
    "mealNotification.disabled": "Desativado",
    "mealNotification.mealTimes": "Horários das Refeições",
    "mealNotification.breakfast": "Café da Manhã",
    "mealNotification.morningSnack": "Lanche Manhã",
    "mealNotification.lunch": "Almoço",
    "mealNotification.afternoonSnack": "Lanche Tarde",
    "mealNotification.dinner": "Jantar",
    "mealNotification.preWorkout": "Pré-Treino",
    "mealNotification.postWorkout": "Pós-Treino",
    "mealNotification.waterReminders": "Lembretes de Água",
    "mealNotification.hydrationThroughDay": "Hidratação ao longo do dia",
    "mealNotification.start": "Início",
    "mealNotification.end": "Fim",
    "mealNotification.intervalHours": "Intervalo (horas)",
    
    // Workout Reminder Card
    "workoutReminder.title": "Lembrete de Treino",
    "workoutReminder.minBeforeWorkout": "min antes do treino",
    "workoutReminder.configure": "Configurar Lembrete",
    "workoutReminder.enableReminders": "Ativar lembretes",
    "workoutReminder.workoutTime": "Hora do treino",
    "workoutReminder.notifyBefore": "Avisar antes",
    "workoutReminder.motivationalMessage": "Mensagem motivacional",
    "workoutReminder.enableNotificationsFirst": "Ative as notificações primeiro para usar lembretes",
    "workoutReminder.timeToTrain": "Hora de Treinar!",
    "workoutReminder.now": "agora",
    "workoutReminder.notificationPreview": "Pré-visualização da notificação",
  },
  "en": {
    // Auth
    "auth.welcomeTo": "Welcome to",
    "auth.journeyStarts": "Your workout journey starts here.",
    "auth.createAccount": "Create Account",
    "auth.login": "Login",
    "auth.yourName": "Your name",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.signUp": "Sign Up",
    "auth.back": "Back",
    "auth.termsOfUse": "Terms of Use",
    "auth.privacyPolicy": "Privacy Policy",
    "auth.loginSuccess": "Login successful!",
    "auth.accountCreated": "Account created successfully!",
    "auth.emailRegistered": "This email is already registered. Try logging in.",
    "auth.invalidCredentials": "Invalid email or password.",
    
    // Home
    "home.rest": "Rest",
    "home.todayWorkout": "Today's workout",
    "home.recoveryDay": "Recovery day",
    "home.progress": "Progress",
    "home.seriesDone": "Sets done",
    "home.totalReps": "Total reps",
    "home.trainingMin": "Training min",
    "home.suggestedExercise": "Suggested exercise",
    "home.focusOn": "Focus on",
    "home.recovery": "Recovery",
    "home.upcomingWorkouts": "Upcoming workouts",
    "home.workoutComplete": "Workout complete! 💪",
    "home.congratsAllExercises": "Congratulations, you completed all exercises for today!",
    "home.exercises": "Exercises",
    "home.suggestedExercisesFor": "Suggested exercises for",
    "home.resetOnboarding": "Reset onboarding",
    "home.resetOnboardingDesc": "Reset your training preferences",
    "home.settings": "Settings",
    
    // Workout
    "workout.restDay": "Rest Day",
    "workout.activeRecovery": "Active Recovery",
    "workout.restImportant": "Rest is as important as training. Take time to recover!",
    "workout.trainingType": "Training Type",
    "workout.strength": "Strength",
    "workout.hypertrophy": "Hypertrophy",
    "workout.endurance": "Endurance",
    "workout.savedExercisesToday": "Saved Exercises Today",
    "workout.restCalculation": "Rest Calculation",
    "workout.baseTime": "Base time",
    "workout.weight": "Weight",
    "workout.reps": "Reps",
    "workout.highSets": "High sets",
    "workout.totalRecommended": "Total recommended",
    "workout.restTimer": "Timer",
    "workout.restEnded": "Rest time finished! 💪",
    "workout.selectExercise": "Select an exercise first",
    "workout.saved": "saved!",
    
    // Nutrition
    "nutrition.title": "Nutrition",
    "nutrition.mealsToday": "Today's Meals",
    "nutrition.noMeals": "You haven't logged any meals yet",
    "nutrition.useScannerHint": "Use the AI scanner above to get started!",
    "nutrition.protein": "Protein",
    "nutrition.carbs": "Carbs",
    "nutrition.fat": "Fat",
    "nutrition.plansRecipes": "Plans & Recipes",
    "nutrition.tipsForAthletes": "Tips for Athletes",
    "nutrition.postWorkout": "Post-workout",
    "nutrition.postWorkoutTip": "Protein + carbs within 2h after workout",
    "nutrition.distributedProtein": "Distributed protein",
    "nutrition.distributedProteinTip": "20-40g per meal is ideal",
    
    // Chat
    "chat.hello": "Hello! I'm",
    "chat.askMe": "Ask me about workouts, nutrition, recovery or your progress!",
    "chat.suggestWorkout": "Suggest workout",
    "chat.recovery": "Recovery",
    "chat.substitute": "Substitute",
    "chat.progressLabel": "Progress",
    "chat.nutritionLabel": "Nutrition",
    "chat.restLabel": "Rest",
    "chat.continuousMode": "Continuous conversation",
    "chat.continuousModeOn": "Continuous mode enabled",
    "chat.continuousModeOff": "Continuous mode disabled",
    "chat.listen": "Listen",
    "chat.playing": "Playing...",
    "chat.recording": "Recording...",
    "chat.tapToCancel": "Tap to cancel",
    "chat.errorCreatingConversation": "Error creating conversation. Login to save history.",
    "chat.errorAI": "Error communicating with AI. Try again.",
    "chat.limitExceeded": "Request limit exceeded. Try again in a few seconds.",
    "chat.creditsExhausted": "Credits exhausted. Add more credits in settings.",
    
    // Alerts
    "alerts.title": "Alerts",
    "alerts.subtitle": "Your training assistant",
    "alerts.workoutRecorded": "Workout recorded! 💪",
    "alerts.streakMilestone": "Streak Milestone!",
    "alerts.consecutiveDays": "consecutive training days!",
    
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Customize your workout",
    "settings.aiName": "Assistant name",
    "settings.calendar": "Calendar",
    "settings.tapToEdit": "Tap to edit",
    "settings.subscription": "Subscription",
    "settings.managePayment": "Manage plan and payment",
    "settings.manage": "Manage",
    "settings.theme": "Theme",
    "settings.changeAppearance": "Change appearance",
    "settings.language": "Language",
    "settings.selectLanguage": "Select language",
    "settings.termsOfUse": "Terms of Use",
    "settings.privacyPolicy": "Privacy Policy",
    "settings.support": "Support",
    "settings.logout": "Log out",
    "settings.logoutDesc": "Sign out of account",
    "settings.lightTheme": "Light theme enabled",
    "settings.darkTheme": "Dark theme enabled",
    "settings.languageUpdated": "Language updated!",
    "settings.aiNameUpdated": "AI name updated!",
    "settings.errorPortal": "Error opening management portal",
    "settings.sessionEnded": "Session ended",
    "settings.errorLogout": "Error logging out",
    
    // BottomNav
    "nav.home": "Home",
    "nav.workout": "Workout",
    "nav.nutrition": "Nutrition",
    "nav.chat": "Chat",
    "nav.alerts": "Alerts",
    
    // Common
    "common.training": "Training",
    "common.rest": "Rest",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.back": "Back",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.incredible": "Incredible!",
    
    // Days
    "days.sunday": "Sunday",
    "days.monday": "Monday",
    "days.tuesday": "Tuesday",
    "days.wednesday": "Wednesday",
    "days.thursday": "Thursday",
    "days.friday": "Friday",
    "days.saturday": "Saturday",
    "days.sun": "Sun",
    "days.mon": "Mon",
    "days.tue": "Tue",
    "days.wed": "Wed",
    "days.thu": "Thu",
    "days.fri": "Fri",
    "days.sat": "Sat",
    
    // AI Workout Generator
    "aiWorkout.title": "AI Workout Generator",
    "aiWorkout.generating": "Generating personalized workout...",
    "aiWorkout.generateFor": "Generate Workout for",
    "aiWorkout.noMuscleGroups": "No muscle groups defined for today",
    "aiWorkout.success": "Workout generated successfully! 💪",
    "aiWorkout.error": "Error generating workout. Try again.",
    "aiWorkout.progress": "Progress",
    "aiWorkout.exercises": "exercises",
    "aiWorkout.duration": "Duration",
    "aiWorkout.level": "Level",
    "aiWorkout.warmup": "Warmup",
    "aiWorkout.cooldown": "Cooldown",
    "aiWorkout.tip": "Tip",
    "aiWorkout.equipment": "Equipment",
    "aiWorkout.useInRecord": "Use in record →",
    "aiWorkout.regenerate": "Generate New Workout",
    "aiWorkout.rest": "rest",
    
    // Food Scanner
    "foodScanner.addMeal": "Add Meal",
    "foodScanner.takePhoto": "Take Photo",
    "foodScanner.gallery": "Gallery",
    "foodScanner.orDescribe": "or describe",
    "foodScanner.exampleDescription": "Ex: 200g grilled chicken, brown rice...",
    "foodScanner.analyzing": "Analyzing with AI...",
    "foodScanner.analysisComplete": "Analysis complete!",
    "foodScanner.foodsIdentified": "food(s) identified",
    "foodScanner.analysisError": "Analysis error",
    "foodScanner.analysisErrorDesc": "Could not analyze the image. Try again.",
    "foodScanner.textAnalysisError": "Could not analyze the description.",
    "foodScanner.addedFood": "added",
    "foodScanner.mealAdded": "Meal added!",
    "foodScanner.kcalRegistered": "kcal registered",
    "foodScanner.identifiedFoods": "Identified foods",
    "foodScanner.total": "Total",
    "foodScanner.protein": "Protein",
    "foodScanner.carbs": "Carbs",
    "foodScanner.fat": "Fat",
    "foodScanner.fiber": "Fiber",
    "foodScanner.aiScanner": "AI Scanner",
    "foodScanner.search": "Search",
    "foodScanner.searchFoods": "Search foods...",
    "foodScanner.suggestions": "Suggestions",
    "foodScanner.postWorkoutSuggestions": "Post-Workout",
    "foodScanner.preWorkoutSuggestions": "Pre-Workout",
    "foodScanner.results": "Results",
    "foodScanner.noFoodFound": "No food found",
    "foodScanner.selected": "Selected",
    "foodScanner.items": "items",
    "foodScanner.newAnalysis": "New Analysis",
    "foodScanner.clear": "Clear",
    "foodScanner.add": "Add",
    "foodScanner.postWorkoutWindow": "Post-Workout Window",
    "foodScanner.preWorkoutPrep": "Pre-Workout Preparation",
    "foodScanner.activeRecovery": "Active Recovery",
    
    // Hydration Card
    "hydration.title": "Hydration",
    "hydration.every": "Every",
    "hydration.min": "min",
    "hydration.configure": "Configure Hydration",
    "hydration.enableReminders": "Enable reminders",
    "hydration.interval": "Interval",
    "hydration.dailyGoal": "Daily goal",
    "hydration.remove": "Remove",
    
    // Streak Card
    "streak.title": "Consistency",
    "streak.recordedToday": "Workout recorded today! 💪",
    "streak.startNew": "Start a new streak!",
    "streak.legendary": "Legendary! Keep it up!",
    "streak.unstoppable": "Unstoppable! 2 weeks!",
    "streak.oneWeek": "One week! Excellent!",
    "streak.dontBreak": "Don't break the streak!",
    "streak.recordWorkout": "Record Workout",
    "streak.days": "DAYS",
    "streak.record": "Record",
    "streak.daysLabel": "days",
    "streak.total": "Total",
    "streak.workouts": "workouts",
    
    // Supplements Card
    "supplements.title": "Supplements",
    "supplements.activeReminders": "active reminders",
    "supplements.newSupplement": "New Supplement",
    "supplements.name": "Name",
    "supplements.namePlaceholder": "Ex: Omega 3, BCAA...",
    "supplements.time": "Time",
    "supplements.addSupplement": "Add Supplement",
    "supplements.noSupplements": "No supplements configured",
    
    // Sleep Card
    "sleep.title": "Sleep & Recovery",
    "sleep.reminderBefore": "Reminder",
    "sleep.minBefore": "min before",
    "sleep.configure": "Configure Sleep",
    "sleep.enableReminders": "Enable reminders",
    "sleep.sleep": "Sleep",
    "sleep.wake": "Wake",
    "sleep.reminderBeforeLabel": "Reminder before",
    "sleep.excellent": "Excellent",
    "sleep.good": "Good",
    "sleep.fair": "Fair",
    "sleep.insufficient": "Insufficient",
    "sleep.sleepEqualsGains": "Sleep = Gains",
    "sleep.recoversMusles": "Recovers muscles",
    
    // Quick Timer Card
    "timer.title": "Quick Timer",
    "timer.restBetweenSets": "Rest between sets",
    "timer.remaining": "remaining",
    "timer.stop": "Stop",
    "timer.restart": "Restart",
    
    // Meal Notification Card
    "mealNotification.title": "Meal Reminders",
    "mealNotification.enableNotificationsFirst": "Enable notifications first",
    "mealNotification.mealsActive": "active meals",
    "mealNotification.disabled": "Disabled",
    "mealNotification.mealTimes": "Meal Times",
    "mealNotification.breakfast": "Breakfast",
    "mealNotification.morningSnack": "Morning Snack",
    "mealNotification.lunch": "Lunch",
    "mealNotification.afternoonSnack": "Afternoon Snack",
    "mealNotification.dinner": "Dinner",
    "mealNotification.preWorkout": "Pre-Workout",
    "mealNotification.postWorkout": "Post-Workout",
    "mealNotification.waterReminders": "Water Reminders",
    "mealNotification.hydrationThroughDay": "Hydration throughout the day",
    "mealNotification.start": "Start",
    "mealNotification.end": "End",
    "mealNotification.intervalHours": "Interval (hours)",
    
    // Workout Reminder Card
    "workoutReminder.title": "Workout Reminder",
    "workoutReminder.minBeforeWorkout": "min before workout",
    "workoutReminder.configure": "Configure Reminder",
    "workoutReminder.enableReminders": "Enable reminders",
    "workoutReminder.workoutTime": "Workout time",
    "workoutReminder.notifyBefore": "Notify before",
    "workoutReminder.motivationalMessage": "Motivational message",
    "workoutReminder.enableNotificationsFirst": "Enable notifications first to use reminders",
    "workoutReminder.timeToTrain": "Time to Train!",
    "workoutReminder.now": "now",
    "workoutReminder.notificationPreview": "Notification preview",
  },
  "es": {
    // Auth
    "auth.welcomeTo": "Bienvenido a",
    "auth.journeyStarts": "Tu viaje de entrenamiento comienza aquí.",
    "auth.createAccount": "Crear Cuenta",
    "auth.login": "Iniciar Sesión",
    "auth.yourName": "Tu nombre",
    "auth.email": "Correo electrónico",
    "auth.password": "Contraseña",
    "auth.noAccount": "¿No tienes cuenta?",
    "auth.hasAccount": "¿Ya tienes cuenta?",
    "auth.signUp": "Registrarse",
    "auth.back": "Volver",
    "auth.termsOfUse": "Términos de Uso",
    "auth.privacyPolicy": "Política de Privacidad",
    "auth.loginSuccess": "¡Inicio de sesión exitoso!",
    "auth.accountCreated": "¡Cuenta creada con éxito!",
    "auth.emailRegistered": "Este correo ya está registrado. Intenta iniciar sesión.",
    "auth.invalidCredentials": "Correo o contraseña incorrectos.",
    
    // Home
    "home.rest": "Descanso",
    "home.todayWorkout": "Entrenamiento de hoy",
    "home.recoveryDay": "Día de recuperación",
    "home.progress": "Progreso",
    "home.seriesDone": "Series hechas",
    "home.totalReps": "Reps totales",
    "home.trainingMin": "Min entreno",
    "home.suggestedExercise": "Ejercicio sugerido",
    "home.focusOn": "Enfoque en",
    "home.recovery": "Recuperación",
    "home.upcomingWorkouts": "Próximos entrenamientos",
    "home.workoutComplete": "¡Entrenamiento completo! 💪",
    "home.congratsAllExercises": "¡Felicidades, completaste todos los ejercicios de hoy!",
    "home.exercises": "Ejercicios",
    "home.suggestedExercisesFor": "Ejercicios sugeridos para",
    "home.resetOnboarding": "Reiniciar onboarding",
    "home.resetOnboardingDesc": "Restablece tus preferencias de entrenamiento",
    "home.settings": "Configuración",
    
    // Workout
    "workout.restDay": "Día de Descanso",
    "workout.activeRecovery": "Recuperación Activa",
    "workout.restImportant": "¡El descanso es tan importante como el entrenamiento. Aprovecha para recuperarte!",
    "workout.trainingType": "Tipo de Entrenamiento",
    "workout.strength": "Fuerza",
    "workout.hypertrophy": "Hipertrofia",
    "workout.endurance": "Resistencia",
    "workout.savedExercisesToday": "Ejercicios Guardados Hoy",
    "workout.restCalculation": "Cálculo del Descanso",
    "workout.baseTime": "Tiempo base",
    "workout.weight": "Peso",
    "workout.reps": "Repeticiones",
    "workout.highSets": "Series altas",
    "workout.totalRecommended": "Total recomendado",
    "workout.restTimer": "Temporizador",
    "workout.restEnded": "¡Tiempo de descanso terminado! 💪",
    "workout.selectExercise": "Selecciona un ejercicio primero",
    "workout.saved": "¡guardado!",
    
    // Nutrition
    "nutrition.title": "Nutrición",
    "nutrition.mealsToday": "Comidas de Hoy",
    "nutrition.noMeals": "Aún no has registrado ninguna comida",
    "nutrition.useScannerHint": "¡Usa el escáner IA arriba para comenzar!",
    "nutrition.protein": "Proteína",
    "nutrition.carbs": "Carbos",
    "nutrition.fat": "Grasa",
    "nutrition.plansRecipes": "Planes y Recetas",
    "nutrition.tipsForAthletes": "Consejos para Atletas",
    "nutrition.postWorkout": "Post-entreno",
    "nutrition.postWorkoutTip": "Proteína + carbos hasta 2h después del entreno",
    "nutrition.distributedProtein": "Proteína distribuida",
    "nutrition.distributedProteinTip": "20-40g por comida es ideal",
    
    // Chat
    "chat.hello": "¡Hola! Soy",
    "chat.askMe": "¡Pregúntame sobre entrenamientos, nutrición, recuperación o tu progreso!",
    "chat.suggestWorkout": "Sugiere entreno",
    "chat.recovery": "Recuperación",
    "chat.substitute": "Sustituir",
    "chat.progressLabel": "Progreso",
    "chat.nutritionLabel": "Nutrición",
    "chat.restLabel": "Descanso",
    "chat.continuousMode": "Conversación continua",
    "chat.continuousModeOn": "Modo continuo activado",
    "chat.continuousModeOff": "Modo continuo desactivado",
    "chat.listen": "Escuchar",
    "chat.playing": "Reproduciendo...",
    "chat.recording": "Grabando...",
    "chat.tapToCancel": "Toca para cancelar",
    "chat.errorCreatingConversation": "Error al crear conversación. Inicia sesión para guardar el historial.",
    "chat.errorAI": "Error al comunicar con la IA. Intenta de nuevo.",
    "chat.limitExceeded": "Límite de solicitudes excedido. Intenta en unos segundos.",
    "chat.creditsExhausted": "Créditos agotados. Añade más créditos en configuración.",
    
    // Alerts
    "alerts.title": "Alertas",
    "alerts.subtitle": "Tu asistente de entrenamiento",
    "alerts.workoutRecorded": "¡Entrenamiento registrado! 💪",
    "alerts.streakMilestone": "¡Hito de Racha!",
    "alerts.consecutiveDays": "¡días consecutivos de entrenamiento!",
    
    // Settings
    "settings.title": "Configuración",
    "settings.subtitle": "Personaliza tu entrenamiento",
    "settings.aiName": "Nombre del asistente",
    "settings.calendar": "Calendario",
    "settings.tapToEdit": "Toca para editar",
    "settings.subscription": "Suscripción",
    "settings.managePayment": "Gestionar plan y pago",
    "settings.manage": "Gestionar",
    "settings.theme": "Tema",
    "settings.changeAppearance": "Cambiar apariencia",
    "settings.language": "Idioma",
    "settings.selectLanguage": "Selecciona el idioma",
    "settings.termsOfUse": "Términos de Uso",
    "settings.privacyPolicy": "Política de Privacidad",
    "settings.support": "Soporte",
    "settings.logout": "Cerrar sesión",
    "settings.logoutDesc": "Salir de la cuenta",
    "settings.lightTheme": "Tema claro activado",
    "settings.darkTheme": "Tema oscuro activado",
    "settings.languageUpdated": "¡Idioma actualizado!",
    "settings.aiNameUpdated": "¡Nombre de IA actualizado!",
    "settings.errorPortal": "Error al abrir portal de gestión",
    "settings.sessionEnded": "Sesión cerrada",
    "settings.errorLogout": "Error al cerrar sesión",
    
    // BottomNav
    "nav.home": "Inicio",
    "nav.workout": "Entreno",
    "nav.nutrition": "Nutrición",
    "nav.chat": "Chat",
    "nav.alerts": "Alertas",
    
    // Common
    "common.training": "Entrenamiento",
    "common.rest": "Descanso",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.back": "Volver",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.incredible": "¡Increíble!",
    
    // Days
    "days.sunday": "Domingo",
    "days.monday": "Lunes",
    "days.tuesday": "Martes",
    "days.wednesday": "Miércoles",
    "days.thursday": "Jueves",
    "days.friday": "Viernes",
    "days.saturday": "Sábado",
    "days.sun": "Dom",
    "days.mon": "Lun",
    "days.tue": "Mar",
    "days.wed": "Mié",
    "days.thu": "Jue",
    "days.fri": "Vie",
    "days.sat": "Sáb",
  },
  "fr": {
    "auth.welcomeTo": "Bienvenue sur",
    "auth.journeyStarts": "Ton parcours d'entraînement commence ici.",
    "auth.createAccount": "Créer un compte",
    "auth.login": "Connexion",
    "auth.yourName": "Ton nom",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.noAccount": "Pas de compte ?",
    "auth.hasAccount": "Déjà un compte ?",
    "auth.signUp": "S'inscrire",
    "auth.back": "Retour",
    "auth.termsOfUse": "Conditions d'utilisation",
    "auth.privacyPolicy": "Politique de confidentialité",
    "auth.loginSuccess": "Connexion réussie !",
    "auth.accountCreated": "Compte créé avec succès !",
    "auth.emailRegistered": "Cet email est déjà enregistré. Essaie de te connecter.",
    "auth.invalidCredentials": "Email ou mot de passe incorrect.",
    "home.rest": "Repos",
    "home.todayWorkout": "Entraînement du jour",
    "home.recoveryDay": "Jour de récupération",
    "home.progress": "Progrès",
    "home.seriesDone": "Séries faites",
    "home.totalReps": "Reps totales",
    "home.trainingMin": "Min entrainement",
    "home.suggestedExercise": "Exercice suggéré",
    "home.focusOn": "Focus sur",
    "home.recovery": "Récupération",
    "home.upcomingWorkouts": "Prochains entraînements",
    "home.workoutComplete": "Entraînement terminé ! 💪",
    "home.congratsAllExercises": "Félicitations, tu as complété tous les exercices d'aujourd'hui !",
    "home.exercises": "Exercices",
    "home.suggestedExercisesFor": "Exercices suggérés pour",
    "home.resetOnboarding": "Refaire l'onboarding",
    "home.resetOnboardingDesc": "Réinitialise tes préférences d'entraînement",
    "home.settings": "Paramètres",
    "workout.restDay": "Jour de Repos",
    "workout.activeRecovery": "Récupération Active",
    "workout.restImportant": "Le repos est aussi important que l'entraînement. Profites-en pour récupérer !",
    "workout.trainingType": "Type d'entraînement",
    "workout.strength": "Force",
    "workout.hypertrophy": "Hypertrophie",
    "workout.endurance": "Endurance",
    "workout.savedExercisesToday": "Exercices sauvegardés aujourd'hui",
    "workout.restCalculation": "Calcul du repos",
    "workout.baseTime": "Temps de base",
    "workout.weight": "Poids",
    "workout.reps": "Répétitions",
    "workout.highSets": "Séries hautes",
    "workout.totalRecommended": "Total recommandé",
    "workout.restTimer": "Minuteur",
    "workout.restEnded": "Temps de repos terminé ! 💪",
    "workout.selectExercise": "Sélectionne d'abord un exercice",
    "workout.saved": "sauvegardé !",
    "nutrition.title": "Nutrition",
    "nutrition.mealsToday": "Repas d'aujourd'hui",
    "nutrition.noMeals": "Tu n'as pas encore enregistré de repas",
    "nutrition.useScannerHint": "Utilise le scanner IA ci-dessus pour commencer !",
    "nutrition.protein": "Protéines",
    "nutrition.carbs": "Glucides",
    "nutrition.fat": "Lipides",
    "nutrition.plansRecipes": "Plans & Recettes",
    "nutrition.tipsForAthletes": "Conseils pour athlètes",
    "nutrition.postWorkout": "Post-entraînement",
    "nutrition.postWorkoutTip": "Protéines + glucides dans les 2h après l'entraînement",
    "nutrition.distributedProtein": "Protéines distribuées",
    "nutrition.distributedProteinTip": "20-40g par repas est idéal",
    "chat.hello": "Bonjour ! Je suis",
    "chat.askMe": "Demande-moi des conseils sur l'entraînement, la nutrition, la récupération ou tes progrès !",
    "chat.suggestWorkout": "Suggère un entraînement",
    "chat.recovery": "Récupération",
    "chat.substitute": "Remplacer",
    "chat.progressLabel": "Progrès",
    "chat.nutritionLabel": "Nutrition",
    "chat.restLabel": "Repos",
    "chat.continuousMode": "Conversation continue",
    "chat.continuousModeOn": "Mode continu activé",
    "chat.continuousModeOff": "Mode continu désactivé",
    "chat.listen": "Écouter",
    "chat.playing": "Lecture...",
    "chat.recording": "Enregistrement...",
    "chat.tapToCancel": "Appuie pour annuler",
    "chat.errorCreatingConversation": "Erreur lors de la création de la conversation. Connecte-toi pour sauvegarder l'historique.",
    "chat.errorAI": "Erreur de communication avec l'IA. Réessaie.",
    "chat.limitExceeded": "Limite de requêtes dépassée. Réessaie dans quelques secondes.",
    "chat.creditsExhausted": "Crédits épuisés. Ajoute plus de crédits dans les paramètres.",
    "alerts.title": "Alertes",
    "alerts.subtitle": "Ton assistant d'entraînement",
    "alerts.workoutRecorded": "Entraînement enregistré ! 💪",
    "alerts.streakMilestone": "Jalon de série !",
    "alerts.consecutiveDays": "jours consécutifs d'entraînement !",
    "settings.title": "Paramètres",
    "settings.subtitle": "Personnalise ton entraînement",
    "settings.aiName": "Nom de l'assistant",
    "settings.calendar": "Calendrier",
    "settings.tapToEdit": "Appuie pour modifier",
    "settings.subscription": "Abonnement",
    "settings.managePayment": "Gérer le plan et le paiement",
    "settings.manage": "Gérer",
    "settings.theme": "Thème",
    "settings.changeAppearance": "Changer l'apparence",
    "settings.language": "Langue",
    "settings.selectLanguage": "Sélectionne la langue",
    "settings.termsOfUse": "Conditions d'utilisation",
    "settings.privacyPolicy": "Politique de confidentialité",
    "settings.support": "Support",
    "settings.logout": "Déconnexion",
    "settings.logoutDesc": "Se déconnecter du compte",
    "settings.lightTheme": "Thème clair activé",
    "settings.darkTheme": "Thème sombre activé",
    "settings.languageUpdated": "Langue mise à jour !",
    "settings.aiNameUpdated": "Nom de l'IA mis à jour !",
    "settings.errorPortal": "Erreur lors de l'ouverture du portail de gestion",
    "settings.sessionEnded": "Session terminée",
    "settings.errorLogout": "Erreur lors de la déconnexion",
    "nav.home": "Accueil",
    "nav.workout": "Entraînement",
    "nav.nutrition": "Nutrition",
    "nav.chat": "Chat",
    "nav.alerts": "Alertes",
    "common.training": "Entraînement",
    "common.rest": "Repos",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.back": "Retour",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.incredible": "Incroyable !",
    "days.sunday": "Dimanche",
    "days.monday": "Lundi",
    "days.tuesday": "Mardi",
    "days.wednesday": "Mercredi",
    "days.thursday": "Jeudi",
    "days.friday": "Vendredi",
    "days.saturday": "Samedi",
    "days.sun": "Dim",
    "days.mon": "Lun",
    "days.tue": "Mar",
    "days.wed": "Mer",
    "days.thu": "Jeu",
    "days.fri": "Ven",
    "days.sat": "Sam",
  },
  "de": {
    "auth.welcomeTo": "Willkommen bei",
    "auth.journeyStarts": "Deine Trainingsreise beginnt hier.",
    "auth.createAccount": "Konto erstellen",
    "auth.login": "Anmelden",
    "auth.yourName": "Dein Name",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.noAccount": "Kein Konto?",
    "auth.hasAccount": "Bereits ein Konto?",
    "auth.signUp": "Registrieren",
    "auth.back": "Zurück",
    "auth.termsOfUse": "Nutzungsbedingungen",
    "auth.privacyPolicy": "Datenschutzrichtlinie",
    "auth.loginSuccess": "Anmeldung erfolgreich!",
    "auth.accountCreated": "Konto erfolgreich erstellt!",
    "auth.emailRegistered": "Diese E-Mail ist bereits registriert. Versuche dich anzumelden.",
    "auth.invalidCredentials": "E-Mail oder Passwort falsch.",
    "home.rest": "Ruhe",
    "home.todayWorkout": "Heutiges Training",
    "home.recoveryDay": "Erholungstag",
    "home.progress": "Fortschritt",
    "home.seriesDone": "Sätze gemacht",
    "home.totalReps": "Gesamte Wdh.",
    "home.trainingMin": "Training Min",
    "home.suggestedExercise": "Empfohlene Übung",
    "home.focusOn": "Fokus auf",
    "home.recovery": "Erholung",
    "home.upcomingWorkouts": "Kommende Trainings",
    "home.workoutComplete": "Training abgeschlossen! 💪",
    "home.congratsAllExercises": "Herzlichen Glückwunsch, du hast alle Übungen für heute abgeschlossen!",
    "home.exercises": "Übungen",
    "home.suggestedExercisesFor": "Empfohlene Übungen für",
    "home.resetOnboarding": "Onboarding zurücksetzen",
    "home.resetOnboardingDesc": "Setze deine Trainingseinstellungen zurück",
    "home.settings": "Einstellungen",
    "workout.restDay": "Ruhetag",
    "workout.activeRecovery": "Aktive Erholung",
    "workout.restImportant": "Ruhe ist genauso wichtig wie Training. Nimm dir Zeit zur Erholung!",
    "workout.trainingType": "Trainingstyp",
    "workout.strength": "Kraft",
    "workout.hypertrophy": "Hypertrophie",
    "workout.endurance": "Ausdauer",
    "workout.savedExercisesToday": "Heute gespeicherte Übungen",
    "workout.restCalculation": "Pausenberechnung",
    "workout.baseTime": "Basiszeit",
    "workout.weight": "Gewicht",
    "workout.reps": "Wiederholungen",
    "workout.highSets": "Hohe Sätze",
    "workout.totalRecommended": "Empfohlene Gesamt",
    "workout.restTimer": "Timer",
    "workout.restEnded": "Pausenzeit beendet! 💪",
    "workout.selectExercise": "Wähle zuerst eine Übung",
    "workout.saved": "gespeichert!",
    "nutrition.title": "Ernährung",
    "nutrition.mealsToday": "Heutige Mahlzeiten",
    "nutrition.noMeals": "Du hast noch keine Mahlzeiten protokolliert",
    "nutrition.useScannerHint": "Benutze den KI-Scanner oben, um loszulegen!",
    "nutrition.protein": "Protein",
    "nutrition.carbs": "Kohlenhydrate",
    "nutrition.fat": "Fett",
    "nutrition.plansRecipes": "Pläne & Rezepte",
    "nutrition.tipsForAthletes": "Tipps für Athleten",
    "nutrition.postWorkout": "Nach dem Training",
    "nutrition.postWorkoutTip": "Protein + Kohlenhydrate bis 2h nach dem Training",
    "nutrition.distributedProtein": "Verteiltes Protein",
    "nutrition.distributedProteinTip": "20-40g pro Mahlzeit ist ideal",
    "chat.hello": "Hallo! Ich bin",
    "chat.askMe": "Frag mich nach Trainings, Ernährung, Erholung oder deinem Fortschritt!",
    "chat.suggestWorkout": "Training vorschlagen",
    "chat.recovery": "Erholung",
    "chat.substitute": "Ersetzen",
    "chat.progressLabel": "Fortschritt",
    "chat.nutritionLabel": "Ernährung",
    "chat.restLabel": "Ruhe",
    "chat.continuousMode": "Kontinuierliche Konversation",
    "chat.continuousModeOn": "Kontinuierlicher Modus aktiviert",
    "chat.continuousModeOff": "Kontinuierlicher Modus deaktiviert",
    "chat.listen": "Anhören",
    "chat.playing": "Abspielen...",
    "chat.recording": "Aufnahme...",
    "chat.tapToCancel": "Tippe zum Abbrechen",
    "chat.errorCreatingConversation": "Fehler beim Erstellen der Konversation. Melde dich an, um den Verlauf zu speichern.",
    "chat.errorAI": "Fehler bei der Kommunikation mit der KI. Versuche es erneut.",
    "chat.limitExceeded": "Anfragelimit überschritten. Versuche es in ein paar Sekunden erneut.",
    "chat.creditsExhausted": "Guthaben aufgebraucht. Füge in den Einstellungen mehr Guthaben hinzu.",
    "alerts.title": "Benachrichtigungen",
    "alerts.subtitle": "Dein Trainingsassistent",
    "alerts.workoutRecorded": "Training aufgezeichnet! 💪",
    "alerts.streakMilestone": "Streak-Meilenstein!",
    "alerts.consecutiveDays": "aufeinanderfolgende Trainingstage!",
    "settings.title": "Einstellungen",
    "settings.subtitle": "Passe dein Training an",
    "settings.aiName": "Assistentenname",
    "settings.calendar": "Kalender",
    "settings.tapToEdit": "Tippe zum Bearbeiten",
    "settings.subscription": "Abonnement",
    "settings.managePayment": "Plan und Zahlung verwalten",
    "settings.manage": "Verwalten",
    "settings.theme": "Theme",
    "settings.changeAppearance": "Aussehen ändern",
    "settings.language": "Sprache",
    "settings.selectLanguage": "Sprache auswählen",
    "settings.termsOfUse": "Nutzungsbedingungen",
    "settings.privacyPolicy": "Datenschutzrichtlinie",
    "settings.support": "Support",
    "settings.logout": "Abmelden",
    "settings.logoutDesc": "Vom Konto abmelden",
    "settings.lightTheme": "Helles Theme aktiviert",
    "settings.darkTheme": "Dunkles Theme aktiviert",
    "settings.languageUpdated": "Sprache aktualisiert!",
    "settings.aiNameUpdated": "KI-Name aktualisiert!",
    "settings.errorPortal": "Fehler beim Öffnen des Verwaltungsportals",
    "settings.sessionEnded": "Sitzung beendet",
    "settings.errorLogout": "Fehler beim Abmelden",
    "nav.home": "Start",
    "nav.workout": "Training",
    "nav.nutrition": "Ernährung",
    "nav.chat": "Chat",
    "nav.alerts": "Benachrichtigungen",
    "common.training": "Training",
    "common.rest": "Ruhe",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.back": "Zurück",
    "common.loading": "Lädt...",
    "common.error": "Fehler",
    "common.success": "Erfolg",
    "common.incredible": "Unglaublich!",
    "days.sunday": "Sonntag",
    "days.monday": "Montag",
    "days.tuesday": "Dienstag",
    "days.wednesday": "Mittwoch",
    "days.thursday": "Donnerstag",
    "days.friday": "Freitag",
    "days.saturday": "Samstag",
    "days.sun": "So",
    "days.mon": "Mo",
    "days.tue": "Di",
    "days.wed": "Mi",
    "days.thu": "Do",
    "days.fri": "Fr",
    "days.sat": "Sa",
  },
  "it": {
    "auth.welcomeTo": "Benvenuto su",
    "auth.journeyStarts": "Il tuo percorso di allenamento inizia qui.",
    "auth.createAccount": "Crea Account",
    "auth.login": "Accedi",
    "auth.yourName": "Il tuo nome",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.noAccount": "Non hai un account?",
    "auth.hasAccount": "Hai già un account?",
    "auth.signUp": "Registrati",
    "auth.back": "Indietro",
    "auth.termsOfUse": "Termini di utilizzo",
    "auth.privacyPolicy": "Informativa sulla privacy",
    "auth.loginSuccess": "Accesso effettuato!",
    "auth.accountCreated": "Account creato con successo!",
    "auth.emailRegistered": "Questa email è già registrata. Prova ad accedere.",
    "auth.invalidCredentials": "Email o password non validi.",
    "home.rest": "Riposo",
    "home.todayWorkout": "Allenamento di oggi",
    "home.recoveryDay": "Giorno di recupero",
    "home.progress": "Progresso",
    "home.seriesDone": "Serie fatte",
    "home.totalReps": "Rep totali",
    "home.trainingMin": "Min allenamento",
    "home.suggestedExercise": "Esercizio suggerito",
    "home.focusOn": "Focus su",
    "home.recovery": "Recupero",
    "home.upcomingWorkouts": "Prossimi allenamenti",
    "home.workoutComplete": "Allenamento completato! 💪",
    "home.congratsAllExercises": "Congratulazioni, hai completato tutti gli esercizi di oggi!",
    "home.exercises": "Esercizi",
    "home.suggestedExercisesFor": "Esercizi suggeriti per",
    "home.resetOnboarding": "Ripristina onboarding",
    "home.resetOnboardingDesc": "Reimposta le tue preferenze di allenamento",
    "home.settings": "Impostazioni",
    "workout.restDay": "Giorno di Riposo",
    "workout.activeRecovery": "Recupero Attivo",
    "workout.restImportant": "Il riposo è importante quanto l'allenamento. Prenditi il tempo per recuperare!",
    "workout.trainingType": "Tipo di Allenamento",
    "workout.strength": "Forza",
    "workout.hypertrophy": "Ipertrofia",
    "workout.endurance": "Resistenza",
    "workout.savedExercisesToday": "Esercizi Salvati Oggi",
    "workout.restCalculation": "Calcolo del Riposo",
    "workout.baseTime": "Tempo base",
    "workout.weight": "Peso",
    "workout.reps": "Ripetizioni",
    "workout.highSets": "Serie alte",
    "workout.totalRecommended": "Totale raccomandato",
    "workout.restTimer": "Timer",
    "workout.restEnded": "Tempo di riposo terminato! 💪",
    "workout.selectExercise": "Seleziona prima un esercizio",
    "workout.saved": "salvato!",
    "nutrition.title": "Nutrizione",
    "nutrition.mealsToday": "Pasti di Oggi",
    "nutrition.noMeals": "Non hai ancora registrato nessun pasto",
    "nutrition.useScannerHint": "Usa lo scanner IA sopra per iniziare!",
    "nutrition.protein": "Proteine",
    "nutrition.carbs": "Carboidrati",
    "nutrition.fat": "Grassi",
    "nutrition.plansRecipes": "Piani e Ricette",
    "nutrition.tipsForAthletes": "Consigli per Atleti",
    "nutrition.postWorkout": "Post-allenamento",
    "nutrition.postWorkoutTip": "Proteine + carboidrati entro 2h dall'allenamento",
    "nutrition.distributedProtein": "Proteine distribuite",
    "nutrition.distributedProteinTip": "20-40g per pasto è ideale",
    "chat.hello": "Ciao! Sono",
    "chat.askMe": "Chiedimi di allenamenti, nutrizione, recupero o i tuoi progressi!",
    "chat.suggestWorkout": "Suggerisci allenamento",
    "chat.recovery": "Recupero",
    "chat.substitute": "Sostituisci",
    "chat.progressLabel": "Progresso",
    "chat.nutritionLabel": "Nutrizione",
    "chat.restLabel": "Riposo",
    "chat.continuousMode": "Conversazione continua",
    "chat.continuousModeOn": "Modalità continua attivata",
    "chat.continuousModeOff": "Modalità continua disattivata",
    "chat.listen": "Ascolta",
    "chat.playing": "Riproduzione...",
    "chat.recording": "Registrazione...",
    "chat.tapToCancel": "Tocca per annullare",
    "chat.errorCreatingConversation": "Errore nella creazione della conversazione. Accedi per salvare la cronologia.",
    "chat.errorAI": "Errore nella comunicazione con l'IA. Riprova.",
    "chat.limitExceeded": "Limite di richieste superato. Riprova tra qualche secondo.",
    "chat.creditsExhausted": "Crediti esauriti. Aggiungi più crediti nelle impostazioni.",
    "alerts.title": "Avvisi",
    "alerts.subtitle": "Il tuo assistente di allenamento",
    "alerts.workoutRecorded": "Allenamento registrato! 💪",
    "alerts.streakMilestone": "Traguardo della serie!",
    "alerts.consecutiveDays": "giorni consecutivi di allenamento!",
    "settings.title": "Impostazioni",
    "settings.subtitle": "Personalizza il tuo allenamento",
    "settings.aiName": "Nome dell'assistente",
    "settings.calendar": "Calendario",
    "settings.tapToEdit": "Tocca per modificare",
    "settings.subscription": "Abbonamento",
    "settings.managePayment": "Gestisci piano e pagamento",
    "settings.manage": "Gestisci",
    "settings.theme": "Tema",
    "settings.changeAppearance": "Cambia aspetto",
    "settings.language": "Lingua",
    "settings.selectLanguage": "Seleziona la lingua",
    "settings.termsOfUse": "Termini di utilizzo",
    "settings.privacyPolicy": "Informativa sulla privacy",
    "settings.support": "Supporto",
    "settings.logout": "Disconnetti",
    "settings.logoutDesc": "Esci dall'account",
    "settings.lightTheme": "Tema chiaro attivato",
    "settings.darkTheme": "Tema scuro attivato",
    "settings.languageUpdated": "Lingua aggiornata!",
    "settings.aiNameUpdated": "Nome IA aggiornato!",
    "settings.errorPortal": "Errore nell'apertura del portale di gestione",
    "settings.sessionEnded": "Sessione terminata",
    "settings.errorLogout": "Errore nella disconnessione",
    "nav.home": "Home",
    "nav.workout": "Allenamento",
    "nav.nutrition": "Nutrizione",
    "nav.chat": "Chat",
    "nav.alerts": "Avvisi",
    "common.training": "Allenamento",
    "common.rest": "Riposo",
    "common.save": "Salva",
    "common.cancel": "Annulla",
    "common.back": "Indietro",
    "common.loading": "Caricamento...",
    "common.error": "Errore",
    "common.success": "Successo",
    "common.incredible": "Incredibile!",
    "days.sunday": "Domenica",
    "days.monday": "Lunedì",
    "days.tuesday": "Martedì",
    "days.wednesday": "Mercoledì",
    "days.thursday": "Giovedì",
    "days.friday": "Venerdì",
    "days.saturday": "Sabato",
    "days.sun": "Dom",
    "days.mon": "Lun",
    "days.tue": "Mar",
    "days.wed": "Mer",
    "days.thu": "Gio",
    "days.fri": "Ven",
    "days.sat": "Sab",
  },
  "nl": {
    "auth.welcomeTo": "Welkom bij",
    "auth.journeyStarts": "Je trainingsreis begint hier.",
    "auth.createAccount": "Account Aanmaken",
    "auth.login": "Inloggen",
    "auth.yourName": "Je naam",
    "auth.email": "E-mail",
    "auth.password": "Wachtwoord",
    "auth.noAccount": "Geen account?",
    "auth.hasAccount": "Al een account?",
    "auth.signUp": "Registreren",
    "auth.back": "Terug",
    "auth.termsOfUse": "Gebruiksvoorwaarden",
    "auth.privacyPolicy": "Privacybeleid",
    "auth.loginSuccess": "Succesvol ingelogd!",
    "auth.accountCreated": "Account succesvol aangemaakt!",
    "auth.emailRegistered": "Dit e-mailadres is al geregistreerd. Probeer in te loggen.",
    "auth.invalidCredentials": "Ongeldige e-mail of wachtwoord.",
    "home.rest": "Rust",
    "home.todayWorkout": "Training van vandaag",
    "home.recoveryDay": "Hersteldag",
    "home.progress": "Voortgang",
    "home.seriesDone": "Sets gedaan",
    "home.totalReps": "Totale reps",
    "home.trainingMin": "Training min",
    "home.suggestedExercise": "Voorgestelde oefening",
    "home.focusOn": "Focus op",
    "home.recovery": "Herstel",
    "home.upcomingWorkouts": "Komende trainingen",
    "home.workoutComplete": "Training voltooid! 💪",
    "home.congratsAllExercises": "Gefeliciteerd, je hebt alle oefeningen van vandaag voltooid!",
    "home.exercises": "Oefeningen",
    "home.suggestedExercisesFor": "Voorgestelde oefeningen voor",
    "home.resetOnboarding": "Onboarding resetten",
    "home.resetOnboardingDesc": "Reset je trainingsvoorkeuren",
    "home.settings": "Instellingen",
    "workout.restDay": "Rustdag",
    "workout.activeRecovery": "Actief Herstel",
    "workout.restImportant": "Rust is net zo belangrijk als training. Neem de tijd om te herstellen!",
    "workout.trainingType": "Trainingstype",
    "workout.strength": "Kracht",
    "workout.hypertrophy": "Hypertrofie",
    "workout.endurance": "Uithoudingsvermogen",
    "workout.savedExercisesToday": "Vandaag Opgeslagen Oefeningen",
    "workout.restCalculation": "Rustberekening",
    "workout.baseTime": "Basistijd",
    "workout.weight": "Gewicht",
    "workout.reps": "Herhalingen",
    "workout.highSets": "Hoge sets",
    "workout.totalRecommended": "Totaal aanbevolen",
    "workout.restTimer": "Timer",
    "workout.restEnded": "Rusttijd voorbij! 💪",
    "workout.selectExercise": "Selecteer eerst een oefening",
    "workout.saved": "opgeslagen!",
    "nutrition.title": "Voeding",
    "nutrition.mealsToday": "Maaltijden van Vandaag",
    "nutrition.noMeals": "Je hebt nog geen maaltijden geregistreerd",
    "nutrition.useScannerHint": "Gebruik de AI-scanner hierboven om te beginnen!",
    "nutrition.protein": "Eiwitten",
    "nutrition.carbs": "Koolhydraten",
    "nutrition.fat": "Vet",
    "nutrition.plansRecipes": "Plannen & Recepten",
    "nutrition.tipsForAthletes": "Tips voor Atleten",
    "nutrition.postWorkout": "Na de training",
    "nutrition.postWorkoutTip": "Eiwitten + koolhydraten binnen 2 uur na training",
    "nutrition.distributedProtein": "Verdeelde eiwitten",
    "nutrition.distributedProteinTip": "20-40g per maaltijd is ideaal",
    "chat.hello": "Hallo! Ik ben",
    "chat.askMe": "Vraag me over trainingen, voeding, herstel of je voortgang!",
    "chat.suggestWorkout": "Stel training voor",
    "chat.recovery": "Herstel",
    "chat.substitute": "Vervangen",
    "chat.progressLabel": "Voortgang",
    "chat.nutritionLabel": "Voeding",
    "chat.restLabel": "Rust",
    "chat.continuousMode": "Continue conversatie",
    "chat.continuousModeOn": "Continue modus ingeschakeld",
    "chat.continuousModeOff": "Continue modus uitgeschakeld",
    "chat.listen": "Luisteren",
    "chat.playing": "Afspelen...",
    "chat.recording": "Opnemen...",
    "chat.tapToCancel": "Tik om te annuleren",
    "chat.errorCreatingConversation": "Fout bij het maken van conversatie. Log in om de geschiedenis op te slaan.",
    "chat.errorAI": "Fout bij communicatie met AI. Probeer opnieuw.",
    "chat.limitExceeded": "Verzoeklimiet overschreden. Probeer het over een paar seconden opnieuw.",
    "chat.creditsExhausted": "Tegoed uitgeput. Voeg meer tegoed toe in instellingen.",
    "alerts.title": "Meldingen",
    "alerts.subtitle": "Je trainingsassistent",
    "alerts.workoutRecorded": "Training geregistreerd! 💪",
    "alerts.streakMilestone": "Streak Mijlpaal!",
    "alerts.consecutiveDays": "opeenvolgende trainingsdagen!",
    "settings.title": "Instellingen",
    "settings.subtitle": "Pas je training aan",
    "settings.aiName": "Assistentnaam",
    "settings.calendar": "Kalender",
    "settings.tapToEdit": "Tik om te bewerken",
    "settings.subscription": "Abonnement",
    "settings.managePayment": "Plan en betaling beheren",
    "settings.manage": "Beheren",
    "settings.theme": "Thema",
    "settings.changeAppearance": "Uiterlijk wijzigen",
    "settings.language": "Taal",
    "settings.selectLanguage": "Selecteer taal",
    "settings.termsOfUse": "Gebruiksvoorwaarden",
    "settings.privacyPolicy": "Privacybeleid",
    "settings.support": "Ondersteuning",
    "settings.logout": "Uitloggen",
    "settings.logoutDesc": "Afmelden van account",
    "settings.lightTheme": "Licht thema geactiveerd",
    "settings.darkTheme": "Donker thema geactiveerd",
    "settings.languageUpdated": "Taal bijgewerkt!",
    "settings.aiNameUpdated": "AI-naam bijgewerkt!",
    "settings.errorPortal": "Fout bij openen beheerportaal",
    "settings.sessionEnded": "Sessie beëindigd",
    "settings.errorLogout": "Fout bij uitloggen",
    "nav.home": "Home",
    "nav.workout": "Training",
    "nav.nutrition": "Voeding",
    "nav.chat": "Chat",
    "nav.alerts": "Meldingen",
    "common.training": "Training",
    "common.rest": "Rust",
    "common.save": "Opslaan",
    "common.cancel": "Annuleren",
    "common.back": "Terug",
    "common.loading": "Laden...",
    "common.error": "Fout",
    "common.success": "Succes",
    "common.incredible": "Ongelooflijk!",
    "days.sunday": "Zondag",
    "days.monday": "Maandag",
    "days.tuesday": "Dinsdag",
    "days.wednesday": "Woensdag",
    "days.thursday": "Donderdag",
    "days.friday": "Vrijdag",
    "days.saturday": "Zaterdag",
    "days.sun": "Zo",
    "days.mon": "Ma",
    "days.tue": "Di",
    "days.wed": "Wo",
    "days.thu": "Do",
    "days.fri": "Vr",
    "days.sat": "Za",
  },
  "ru": {
    "auth.welcomeTo": "Добро пожаловать в",
    "auth.journeyStarts": "Твой путь тренировок начинается здесь.",
    "auth.createAccount": "Создать аккаунт",
    "auth.login": "Войти",
    "auth.yourName": "Твоё имя",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.noAccount": "Нет аккаунта?",
    "auth.hasAccount": "Уже есть аккаунт?",
    "auth.signUp": "Регистрация",
    "auth.back": "Назад",
    "auth.termsOfUse": "Условия использования",
    "auth.privacyPolicy": "Политика конфиденциальности",
    "auth.loginSuccess": "Успешный вход!",
    "auth.accountCreated": "Аккаунт успешно создан!",
    "auth.emailRegistered": "Этот email уже зарегистрирован. Попробуй войти.",
    "auth.invalidCredentials": "Неверный email или пароль.",
    "home.rest": "Отдых",
    "home.todayWorkout": "Тренировка сегодня",
    "home.recoveryDay": "День восстановления",
    "home.progress": "Прогресс",
    "home.seriesDone": "Сделано подходов",
    "home.totalReps": "Всего повторений",
    "home.trainingMin": "Мин тренировки",
    "home.suggestedExercise": "Рекомендуемое упражнение",
    "home.focusOn": "Фокус на",
    "home.recovery": "Восстановление",
    "home.upcomingWorkouts": "Предстоящие тренировки",
    "home.workoutComplete": "Тренировка завершена! 💪",
    "home.congratsAllExercises": "Поздравляем, ты выполнил все упражнения на сегодня!",
    "home.exercises": "Упражнения",
    "home.suggestedExercisesFor": "Рекомендуемые упражнения для",
    "home.resetOnboarding": "Сбросить онбординг",
    "home.resetOnboardingDesc": "Сбросить настройки тренировок",
    "home.settings": "Настройки",
    "workout.restDay": "День отдыха",
    "workout.activeRecovery": "Активное восстановление",
    "workout.restImportant": "Отдых так же важен, как тренировка. Используй время для восстановления!",
    "workout.trainingType": "Тип тренировки",
    "workout.strength": "Сила",
    "workout.hypertrophy": "Гипертрофия",
    "workout.endurance": "Выносливость",
    "workout.savedExercisesToday": "Сохранённые упражнения сегодня",
    "workout.restCalculation": "Расчёт отдыха",
    "workout.baseTime": "Базовое время",
    "workout.weight": "Вес",
    "workout.reps": "Повторения",
    "workout.highSets": "Много подходов",
    "workout.totalRecommended": "Рекомендуемый итог",
    "workout.restTimer": "Таймер",
    "workout.restEnded": "Время отдыха закончилось! 💪",
    "workout.selectExercise": "Сначала выбери упражнение",
    "workout.saved": "сохранено!",
    "nutrition.title": "Питание",
    "nutrition.mealsToday": "Приёмы пищи сегодня",
    "nutrition.noMeals": "Ты ещё не записал ни одного приёма пищи",
    "nutrition.useScannerHint": "Используй ИИ-сканер выше, чтобы начать!",
    "nutrition.protein": "Белок",
    "nutrition.carbs": "Углеводы",
    "nutrition.fat": "Жиры",
    "nutrition.plansRecipes": "Планы и рецепты",
    "nutrition.tipsForAthletes": "Советы для атлетов",
    "nutrition.postWorkout": "После тренировки",
    "nutrition.postWorkoutTip": "Белок + углеводы в течение 2 часов после тренировки",
    "nutrition.distributedProtein": "Распределённый белок",
    "nutrition.distributedProteinTip": "20-40г на приём пищи — идеально",
    "chat.hello": "Привет! Я",
    "chat.askMe": "Спроси меня о тренировках, питании, восстановлении или твоём прогрессе!",
    "chat.suggestWorkout": "Предложить тренировку",
    "chat.recovery": "Восстановление",
    "chat.substitute": "Заменить",
    "chat.progressLabel": "Прогресс",
    "chat.nutritionLabel": "Питание",
    "chat.restLabel": "Отдых",
    "chat.continuousMode": "Непрерывный разговор",
    "chat.continuousModeOn": "Непрерывный режим включён",
    "chat.continuousModeOff": "Непрерывный режим выключен",
    "chat.listen": "Слушать",
    "chat.playing": "Воспроизведение...",
    "chat.recording": "Запись...",
    "chat.tapToCancel": "Нажми для отмены",
    "chat.errorCreatingConversation": "Ошибка создания разговора. Войди, чтобы сохранить историю.",
    "chat.errorAI": "Ошибка связи с ИИ. Попробуй снова.",
    "chat.limitExceeded": "Превышен лимит запросов. Попробуй через несколько секунд.",
    "chat.creditsExhausted": "Кредиты исчерпаны. Добавь больше кредитов в настройках.",
    "alerts.title": "Уведомления",
    "alerts.subtitle": "Твой тренировочный ассистент",
    "alerts.workoutRecorded": "Тренировка записана! 💪",
    "alerts.streakMilestone": "Серия Достижение!",
    "alerts.consecutiveDays": "дней подряд тренировок!",
    "settings.title": "Настройки",
    "settings.subtitle": "Настрой свою тренировку",
    "settings.aiName": "Имя ассистента",
    "settings.calendar": "Календарь",
    "settings.tapToEdit": "Нажми для редактирования",
    "settings.subscription": "Подписка",
    "settings.managePayment": "Управление планом и оплатой",
    "settings.manage": "Управление",
    "settings.theme": "Тема",
    "settings.changeAppearance": "Изменить внешний вид",
    "settings.language": "Язык",
    "settings.selectLanguage": "Выбери язык",
    "settings.termsOfUse": "Условия использования",
    "settings.privacyPolicy": "Политика конфиденциальности",
    "settings.support": "Поддержка",
    "settings.logout": "Выйти",
    "settings.logoutDesc": "Выйти из аккаунта",
    "settings.lightTheme": "Светлая тема включена",
    "settings.darkTheme": "Тёмная тема включена",
    "settings.languageUpdated": "Язык обновлён!",
    "settings.aiNameUpdated": "Имя ИИ обновлено!",
    "settings.errorPortal": "Ошибка открытия портала управления",
    "settings.sessionEnded": "Сессия завершена",
    "settings.errorLogout": "Ошибка выхода",
    "nav.home": "Главная",
    "nav.workout": "Тренировка",
    "nav.nutrition": "Питание",
    "nav.chat": "Чат",
    "nav.alerts": "Уведомления",
    "common.training": "Тренировка",
    "common.rest": "Отдых",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.back": "Назад",
    "common.loading": "Загрузка...",
    "common.error": "Ошибка",
    "common.success": "Успех",
    "common.incredible": "Невероятно!",
    "days.sunday": "Воскресенье",
    "days.monday": "Понедельник",
    "days.tuesday": "Вторник",
    "days.wednesday": "Среда",
    "days.thursday": "Четверг",
    "days.friday": "Пятница",
    "days.saturday": "Суббота",
    "days.sun": "Вс",
    "days.mon": "Пн",
    "days.tue": "Вт",
    "days.wed": "Ср",
    "days.thu": "Чт",
    "days.fri": "Пт",
    "days.sat": "Сб",
  },
  "zh": {
    "auth.welcomeTo": "欢迎来到",
    "auth.journeyStarts": "您的健身之旅从这里开始。",
    "auth.createAccount": "创建账户",
    "auth.login": "登录",
    "auth.yourName": "您的名字",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.noAccount": "没有账户？",
    "auth.hasAccount": "已有账户？",
    "auth.signUp": "注册",
    "auth.back": "返回",
    "auth.termsOfUse": "使用条款",
    "auth.privacyPolicy": "隐私政策",
    "auth.loginSuccess": "登录成功！",
    "auth.accountCreated": "账户创建成功！",
    "auth.emailRegistered": "该邮箱已注册。请尝试登录。",
    "auth.invalidCredentials": "邮箱或密码错误。",
    "home.rest": "休息",
    "home.todayWorkout": "今日训练",
    "home.recoveryDay": "恢复日",
    "home.progress": "进度",
    "home.seriesDone": "已完成组数",
    "home.totalReps": "总次数",
    "home.trainingMin": "训练分钟",
    "home.suggestedExercise": "推荐练习",
    "home.focusOn": "专注于",
    "home.recovery": "恢复",
    "home.upcomingWorkouts": "即将到来的训练",
    "home.workoutComplete": "训练完成！💪",
    "home.congratsAllExercises": "恭喜，您完成了今天所有的练习！",
    "home.exercises": "练习",
    "home.suggestedExercisesFor": "推荐练习",
    "home.resetOnboarding": "重置引导",
    "home.resetOnboardingDesc": "重置您的训练偏好",
    "home.settings": "设置",
    "workout.restDay": "休息日",
    "workout.activeRecovery": "积极恢复",
    "workout.restImportant": "休息和训练一样重要。花时间恢复吧！",
    "workout.trainingType": "训练类型",
    "workout.strength": "力量",
    "workout.hypertrophy": "增肌",
    "workout.endurance": "耐力",
    "workout.savedExercisesToday": "今日已保存练习",
    "workout.restCalculation": "休息计算",
    "workout.baseTime": "基础时间",
    "workout.weight": "重量",
    "workout.reps": "次数",
    "workout.highSets": "高组数",
    "workout.totalRecommended": "推荐总计",
    "workout.restTimer": "计时器",
    "workout.restEnded": "休息时间结束！💪",
    "workout.selectExercise": "请先选择一个练习",
    "workout.saved": "已保存！",
    "nutrition.title": "营养",
    "nutrition.mealsToday": "今日餐食",
    "nutrition.noMeals": "您还没有记录任何餐食",
    "nutrition.useScannerHint": "使用上方的AI扫描器开始！",
    "nutrition.protein": "蛋白质",
    "nutrition.carbs": "碳水",
    "nutrition.fat": "脂肪",
    "nutrition.plansRecipes": "计划与食谱",
    "nutrition.tipsForAthletes": "运动员建议",
    "nutrition.postWorkout": "训练后",
    "nutrition.postWorkoutTip": "训练后2小时内摄入蛋白质+碳水",
    "nutrition.distributedProtein": "分配蛋白质",
    "nutrition.distributedProteinTip": "每餐20-40克最理想",
    "chat.hello": "你好！我是",
    "chat.askMe": "问我关于训练、营养、恢复或您的进度！",
    "chat.suggestWorkout": "推荐训练",
    "chat.recovery": "恢复",
    "chat.substitute": "替换",
    "chat.progressLabel": "进度",
    "chat.nutritionLabel": "营养",
    "chat.restLabel": "休息",
    "chat.continuousMode": "连续对话",
    "chat.continuousModeOn": "连续模式已开启",
    "chat.continuousModeOff": "连续模式已关闭",
    "chat.listen": "收听",
    "chat.playing": "播放中...",
    "chat.recording": "录音中...",
    "chat.tapToCancel": "点击取消",
    "chat.errorCreatingConversation": "创建对话时出错。请登录以保存历史记录。",
    "chat.errorAI": "与AI通信时出错。请重试。",
    "chat.limitExceeded": "请求超出限制。请稍后再试。",
    "chat.creditsExhausted": "积分已用完。请在设置中添加更多积分。",
    "alerts.title": "提醒",
    "alerts.subtitle": "您的训练助手",
    "alerts.workoutRecorded": "训练已记录！💪",
    "alerts.streakMilestone": "连续里程碑！",
    "alerts.consecutiveDays": "连续训练天数！",
    "settings.title": "设置",
    "settings.subtitle": "自定义您的训练",
    "settings.aiName": "助手名称",
    "settings.calendar": "日历",
    "settings.tapToEdit": "点击编辑",
    "settings.subscription": "订阅",
    "settings.managePayment": "管理计划和付款",
    "settings.manage": "管理",
    "settings.theme": "主题",
    "settings.changeAppearance": "更改外观",
    "settings.language": "语言",
    "settings.selectLanguage": "选择语言",
    "settings.termsOfUse": "使用条款",
    "settings.privacyPolicy": "隐私政策",
    "settings.support": "支持",
    "settings.logout": "退出登录",
    "settings.logoutDesc": "退出账户",
    "settings.lightTheme": "浅色主题已启用",
    "settings.darkTheme": "深色主题已启用",
    "settings.languageUpdated": "语言已更新！",
    "settings.aiNameUpdated": "AI名称已更新！",
    "settings.errorPortal": "打开管理门户时出错",
    "settings.sessionEnded": "会话已结束",
    "settings.errorLogout": "退出登录时出错",
    "nav.home": "首页",
    "nav.workout": "训练",
    "nav.nutrition": "营养",
    "nav.chat": "聊天",
    "nav.alerts": "提醒",
    "common.training": "训练",
    "common.rest": "休息",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.back": "返回",
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.success": "成功",
    "common.incredible": "太棒了！",
    "days.sunday": "星期日",
    "days.monday": "星期一",
    "days.tuesday": "星期二",
    "days.wednesday": "星期三",
    "days.thursday": "星期四",
    "days.friday": "星期五",
    "days.saturday": "星期六",
    "days.sun": "日",
    "days.mon": "一",
    "days.tue": "二",
    "days.wed": "三",
    "days.thu": "四",
    "days.fri": "五",
    "days.sat": "六",
  },
  "ja": {
    "auth.welcomeTo": "ようこそ",
    "auth.journeyStarts": "あなたのワークアウトの旅はここから始まります。",
    "auth.createAccount": "アカウント作成",
    "auth.login": "ログイン",
    "auth.yourName": "お名前",
    "auth.email": "メール",
    "auth.password": "パスワード",
    "auth.noAccount": "アカウントがない？",
    "auth.hasAccount": "すでにアカウントをお持ち？",
    "auth.signUp": "登録",
    "auth.back": "戻る",
    "auth.termsOfUse": "利用規約",
    "auth.privacyPolicy": "プライバシーポリシー",
    "auth.loginSuccess": "ログイン成功！",
    "auth.accountCreated": "アカウントが作成されました！",
    "auth.emailRegistered": "このメールアドレスはすでに登録されています。ログインしてみてください。",
    "auth.invalidCredentials": "メールアドレスまたはパスワードが無効です。",
    "home.rest": "休息",
    "home.todayWorkout": "今日のワークアウト",
    "home.recoveryDay": "回復日",
    "home.progress": "進捗",
    "home.seriesDone": "完了セット",
    "home.totalReps": "総レップ",
    "home.trainingMin": "トレーニング分",
    "home.suggestedExercise": "おすすめエクササイズ",
    "home.focusOn": "フォーカス",
    "home.recovery": "回復",
    "home.upcomingWorkouts": "今後のワークアウト",
    "home.workoutComplete": "ワークアウト完了！💪",
    "home.congratsAllExercises": "おめでとう、今日のすべてのエクササイズを完了しました！",
    "home.exercises": "エクササイズ",
    "home.suggestedExercisesFor": "おすすめエクササイズ",
    "home.resetOnboarding": "オンボーディングをリセット",
    "home.resetOnboardingDesc": "トレーニング設定をリセット",
    "home.settings": "設定",
    "workout.restDay": "休息日",
    "workout.activeRecovery": "アクティブリカバリー",
    "workout.restImportant": "休息はトレーニングと同じくらい重要です。回復の時間を取りましょう！",
    "workout.trainingType": "トレーニングタイプ",
    "workout.strength": "筋力",
    "workout.hypertrophy": "筋肥大",
    "workout.endurance": "持久力",
    "workout.savedExercisesToday": "今日保存したエクササイズ",
    "workout.restCalculation": "休息計算",
    "workout.baseTime": "基本時間",
    "workout.weight": "重量",
    "workout.reps": "レップ",
    "workout.highSets": "ハイセット",
    "workout.totalRecommended": "推奨合計",
    "workout.restTimer": "タイマー",
    "workout.restEnded": "休息時間終了！💪",
    "workout.selectExercise": "まずエクササイズを選択してください",
    "workout.saved": "保存しました！",
    "nutrition.title": "栄養",
    "nutrition.mealsToday": "今日の食事",
    "nutrition.noMeals": "まだ食事を記録していません",
    "nutrition.useScannerHint": "上のAIスキャナーを使って始めましょう！",
    "nutrition.protein": "タンパク質",
    "nutrition.carbs": "炭水化物",
    "nutrition.fat": "脂質",
    "nutrition.plansRecipes": "プラン＆レシピ",
    "nutrition.tipsForAthletes": "アスリートのためのヒント",
    "nutrition.postWorkout": "ポストワークアウト",
    "nutrition.postWorkoutTip": "ワークアウト後2時間以内にタンパク質+炭水化物",
    "nutrition.distributedProtein": "分散タンパク質",
    "nutrition.distributedProteinTip": "1食あたり20-40gが理想的",
    "chat.hello": "こんにちは！私は",
    "chat.askMe": "ワークアウト、栄養、回復、またはあなたの進捗について聞いてください！",
    "chat.suggestWorkout": "ワークアウトを提案",
    "chat.recovery": "回復",
    "chat.substitute": "置き換え",
    "chat.progressLabel": "進捗",
    "chat.nutritionLabel": "栄養",
    "chat.restLabel": "休息",
    "chat.continuousMode": "連続会話",
    "chat.continuousModeOn": "連続モードオン",
    "chat.continuousModeOff": "連続モードオフ",
    "chat.listen": "聴く",
    "chat.playing": "再生中...",
    "chat.recording": "録音中...",
    "chat.tapToCancel": "キャンセルするにはタップ",
    "chat.errorCreatingConversation": "会話の作成中にエラー。履歴を保存するにはログインしてください。",
    "chat.errorAI": "AIとの通信中にエラー。もう一度お試しください。",
    "chat.limitExceeded": "リクエスト制限を超えました。数秒後に再試行してください。",
    "chat.creditsExhausted": "クレジットが不足しています。設定でクレジットを追加してください。",
    "alerts.title": "アラート",
    "alerts.subtitle": "あなたのトレーニングアシスタント",
    "alerts.workoutRecorded": "ワークアウト記録！💪",
    "alerts.streakMilestone": "ストリークマイルストーン！",
    "alerts.consecutiveDays": "連続トレーニング日！",
    "settings.title": "設定",
    "settings.subtitle": "ワークアウトをカスタマイズ",
    "settings.aiName": "アシスタント名",
    "settings.calendar": "カレンダー",
    "settings.tapToEdit": "タップして編集",
    "settings.subscription": "サブスクリプション",
    "settings.managePayment": "プランと支払いを管理",
    "settings.manage": "管理",
    "settings.theme": "テーマ",
    "settings.changeAppearance": "外観を変更",
    "settings.language": "言語",
    "settings.selectLanguage": "言語を選択",
    "settings.termsOfUse": "利用規約",
    "settings.privacyPolicy": "プライバシーポリシー",
    "settings.support": "サポート",
    "settings.logout": "ログアウト",
    "settings.logoutDesc": "アカウントからサインアウト",
    "settings.lightTheme": "ライトテーマが有効",
    "settings.darkTheme": "ダークテーマが有効",
    "settings.languageUpdated": "言語が更新されました！",
    "settings.aiNameUpdated": "AI名が更新されました！",
    "settings.errorPortal": "管理ポータルを開く際にエラー",
    "settings.sessionEnded": "セッション終了",
    "settings.errorLogout": "ログアウト中にエラー",
    "nav.home": "ホーム",
    "nav.workout": "ワークアウト",
    "nav.nutrition": "栄養",
    "nav.chat": "チャット",
    "nav.alerts": "アラート",
    "common.training": "トレーニング",
    "common.rest": "休息",
    "common.save": "保存",
    "common.cancel": "キャンセル",
    "common.back": "戻る",
    "common.loading": "読み込み中...",
    "common.error": "エラー",
    "common.success": "成功",
    "common.incredible": "素晴らしい！",
    "days.sunday": "日曜日",
    "days.monday": "月曜日",
    "days.tuesday": "火曜日",
    "days.wednesday": "水曜日",
    "days.thursday": "木曜日",
    "days.friday": "金曜日",
    "days.saturday": "土曜日",
    "days.sun": "日",
    "days.mon": "月",
    "days.tue": "火",
    "days.wed": "水",
    "days.thu": "木",
    "days.fri": "金",
    "days.sat": "土",
  },
  "ko": {
    "auth.welcomeTo": "환영합니다",
    "auth.journeyStarts": "당신의 운동 여정이 여기서 시작됩니다.",
    "auth.createAccount": "계정 만들기",
    "auth.login": "로그인",
    "auth.yourName": "이름",
    "auth.email": "이메일",
    "auth.password": "비밀번호",
    "auth.noAccount": "계정이 없으신가요?",
    "auth.hasAccount": "이미 계정이 있으신가요?",
    "auth.signUp": "가입",
    "auth.back": "뒤로",
    "auth.termsOfUse": "이용약관",
    "auth.privacyPolicy": "개인정보 처리방침",
    "auth.loginSuccess": "로그인 성공!",
    "auth.accountCreated": "계정이 성공적으로 생성되었습니다!",
    "auth.emailRegistered": "이 이메일은 이미 등록되어 있습니다. 로그인을 시도해 주세요.",
    "auth.invalidCredentials": "이메일 또는 비밀번호가 잘못되었습니다.",
    "home.rest": "휴식",
    "home.todayWorkout": "오늘의 운동",
    "home.recoveryDay": "회복일",
    "home.progress": "진행",
    "home.seriesDone": "완료한 세트",
    "home.totalReps": "총 반복",
    "home.trainingMin": "훈련 분",
    "home.suggestedExercise": "추천 운동",
    "home.focusOn": "집중",
    "home.recovery": "회복",
    "home.upcomingWorkouts": "다가오는 운동",
    "home.workoutComplete": "운동 완료! 💪",
    "home.congratsAllExercises": "축하합니다, 오늘의 모든 운동을 완료했습니다!",
    "home.exercises": "운동",
    "home.suggestedExercisesFor": "추천 운동",
    "home.resetOnboarding": "온보딩 리셋",
    "home.resetOnboardingDesc": "훈련 환경설정 초기화",
    "home.settings": "설정",
    "workout.restDay": "휴식일",
    "workout.activeRecovery": "활성 회복",
    "workout.restImportant": "휴식은 훈련만큼 중요합니다. 회복할 시간을 가지세요!",
    "workout.trainingType": "훈련 유형",
    "workout.strength": "근력",
    "workout.hypertrophy": "근비대",
    "workout.endurance": "지구력",
    "workout.savedExercisesToday": "오늘 저장한 운동",
    "workout.restCalculation": "휴식 계산",
    "workout.baseTime": "기본 시간",
    "workout.weight": "중량",
    "workout.reps": "반복",
    "workout.highSets": "높은 세트",
    "workout.totalRecommended": "추천 총계",
    "workout.restTimer": "타이머",
    "workout.restEnded": "휴식 시간 종료! 💪",
    "workout.selectExercise": "먼저 운동을 선택하세요",
    "workout.saved": "저장됨!",
    "nutrition.title": "영양",
    "nutrition.mealsToday": "오늘의 식사",
    "nutrition.noMeals": "아직 기록된 식사가 없습니다",
    "nutrition.useScannerHint": "위의 AI 스캐너를 사용해 시작하세요!",
    "nutrition.protein": "단백질",
    "nutrition.carbs": "탄수화물",
    "nutrition.fat": "지방",
    "nutrition.plansRecipes": "계획 및 레시피",
    "nutrition.tipsForAthletes": "운동선수를 위한 팁",
    "nutrition.postWorkout": "운동 후",
    "nutrition.postWorkoutTip": "운동 후 2시간 이내 단백질 + 탄수화물",
    "nutrition.distributedProtein": "분산 단백질",
    "nutrition.distributedProteinTip": "식사당 20-40g이 이상적",
    "chat.hello": "안녕하세요! 저는",
    "chat.askMe": "운동, 영양, 회복 또는 진행 상황에 대해 물어보세요!",
    "chat.suggestWorkout": "운동 제안",
    "chat.recovery": "회복",
    "chat.substitute": "대체",
    "chat.progressLabel": "진행",
    "chat.nutritionLabel": "영양",
    "chat.restLabel": "휴식",
    "chat.continuousMode": "연속 대화",
    "chat.continuousModeOn": "연속 모드 활성화",
    "chat.continuousModeOff": "연속 모드 비활성화",
    "chat.listen": "듣기",
    "chat.playing": "재생 중...",
    "chat.recording": "녹음 중...",
    "chat.tapToCancel": "취소하려면 탭",
    "chat.errorCreatingConversation": "대화 생성 중 오류. 기록을 저장하려면 로그인하세요.",
    "chat.errorAI": "AI와 통신 중 오류. 다시 시도해 주세요.",
    "chat.limitExceeded": "요청 한도 초과. 몇 초 후 다시 시도하세요.",
    "chat.creditsExhausted": "크레딧이 소진되었습니다. 설정에서 크레딧을 추가하세요.",
    "alerts.title": "알림",
    "alerts.subtitle": "당신의 훈련 어시스턴트",
    "alerts.workoutRecorded": "운동 기록됨! 💪",
    "alerts.streakMilestone": "연속 마일스톤!",
    "alerts.consecutiveDays": "연속 훈련 일!",
    "settings.title": "설정",
    "settings.subtitle": "운동을 맞춤 설정하세요",
    "settings.aiName": "어시스턴트 이름",
    "settings.calendar": "캘린더",
    "settings.tapToEdit": "탭하여 편집",
    "settings.subscription": "구독",
    "settings.managePayment": "플랜 및 결제 관리",
    "settings.manage": "관리",
    "settings.theme": "테마",
    "settings.changeAppearance": "외관 변경",
    "settings.language": "언어",
    "settings.selectLanguage": "언어 선택",
    "settings.termsOfUse": "이용약관",
    "settings.privacyPolicy": "개인정보 처리방침",
    "settings.support": "지원",
    "settings.logout": "로그아웃",
    "settings.logoutDesc": "계정에서 로그아웃",
    "settings.lightTheme": "라이트 테마 활성화됨",
    "settings.darkTheme": "다크 테마 활성화됨",
    "settings.languageUpdated": "언어가 업데이트되었습니다!",
    "settings.aiNameUpdated": "AI 이름이 업데이트되었습니다!",
    "settings.errorPortal": "관리 포털 열기 오류",
    "settings.sessionEnded": "세션 종료",
    "settings.errorLogout": "로그아웃 오류",
    "nav.home": "홈",
    "nav.workout": "운동",
    "nav.nutrition": "영양",
    "nav.chat": "채팅",
    "nav.alerts": "알림",
    "common.training": "훈련",
    "common.rest": "휴식",
    "common.save": "저장",
    "common.cancel": "취소",
    "common.back": "뒤로",
    "common.loading": "로딩 중...",
    "common.error": "오류",
    "common.success": "성공",
    "common.incredible": "대단해요!",
    "days.sunday": "일요일",
    "days.monday": "월요일",
    "days.tuesday": "화요일",
    "days.wednesday": "수요일",
    "days.thursday": "목요일",
    "days.friday": "금요일",
    "days.saturday": "토요일",
    "days.sun": "일",
    "days.mon": "월",
    "days.tue": "화",
    "days.wed": "수",
    "days.thu": "목",
    "days.fri": "금",
    "days.sat": "토",
  },
};

const getTranslations = (lang: Language): Record<string, string> => {
  return translations[lang] || translations["pt-PT"];
};

export { LanguageContext, getTranslations };
