import { useState, useEffect, createContext, useContext } from "react";

export type Language = 
  | "pt-PT" 
  | "pt-BR" 
  | "en" 
  | "es" 
  | "fr" 
  | "de" 
  | "it" 
  | "nl" 
  | "ru" 
  | "zh" 
  | "ja" 
  | "ko";

export interface LanguageOption {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: LanguageOption[] = [
  { code: "pt-PT", name: "Portuguese (Portugal)", nativeName: "Português (Portugal)", flag: "🇵🇹" },
  { code: "pt-BR", name: "Portuguese (Brazil)", nativeName: "Português (Brasil)", flag: "🇧🇷" },
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
];

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getLanguageOption: (code: Language) => LanguageOption | undefined;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    // Fallback for when context is not available
    const [language, setLanguageState] = useState<Language>(() => {
      const saved = localStorage.getItem("liftmate_language");
      return (saved as Language) || "pt-PT";
    });

    const setLanguage = (lang: Language) => {
      setLanguageState(lang);
      localStorage.setItem("liftmate_language", lang);
    };

    const t = (key: string) => {
      const translations = getTranslations(language);
      return translations[key] || key;
    };

    const getLanguageOption = (code: Language) => {
      return languages.find(l => l.code === code);
    };

    return { language, setLanguage, t, getLanguageOption };
  }
  return context;
};

// Translations object
const translations: Record<Language, Record<string, string>> = {
  "pt-PT": {
    // Settings
    "settings.title": "Definições",
    "settings.subtitle": "Personaliza o teu treino",
    "settings.aiName": "Nome do assistente",
    "settings.calendar": "Calendário",
    "settings.tapToEdit": "Toca para editar",
    "settings.subscription": "Subscrição",
    "settings.managePayment": "Gerir plano e pagamento",
    "settings.manage": "Gerir",
    "settings.theme": "Tema",
    "settings.changeAppearance": "Altera a aparência",
    "settings.language": "Idioma",
    "settings.selectLanguage": "Seleciona o idioma",
    "settings.termsOfUse": "Termos de Uso",
    "settings.privacyPolicy": "Política de Privacidade",
    "settings.support": "Suporte",
    "settings.logout": "Terminar sessão",
    "settings.logoutDesc": "Sair da conta",
    "settings.lightTheme": "Tema claro ativado",
    "settings.darkTheme": "Tema escuro ativado",
    "settings.languageUpdated": "Idioma atualizado!",
    // Common
    "common.training": "Treino",
    "common.rest": "Descanso",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.back": "Voltar",
    // Days
    "days.monday": "Segunda-feira",
    "days.tuesday": "Terça-feira",
    "days.wednesday": "Quarta-feira",
    "days.thursday": "Quinta-feira",
    "days.friday": "Sexta-feira",
    "days.saturday": "Sábado",
    "days.sunday": "Domingo",
  },
  "pt-BR": {
    "settings.title": "Configurações",
    "settings.subtitle": "Personalize seu treino",
    "settings.aiName": "Nome do assistente",
    "settings.calendar": "Calendário",
    "settings.tapToEdit": "Toque para editar",
    "settings.subscription": "Assinatura",
    "settings.managePayment": "Gerenciar plano e pagamento",
    "settings.manage": "Gerenciar",
    "settings.theme": "Tema",
    "settings.changeAppearance": "Alterar aparência",
    "settings.language": "Idioma",
    "settings.selectLanguage": "Selecione o idioma",
    "settings.termsOfUse": "Termos de Uso",
    "settings.privacyPolicy": "Política de Privacidade",
    "settings.support": "Suporte",
    "settings.logout": "Encerrar sessão",
    "settings.logoutDesc": "Sair da conta",
    "settings.lightTheme": "Tema claro ativado",
    "settings.darkTheme": "Tema escuro ativado",
    "settings.languageUpdated": "Idioma atualizado!",
    "common.training": "Treino",
    "common.rest": "Descanso",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.back": "Voltar",
    "days.monday": "Segunda-feira",
    "days.tuesday": "Terça-feira",
    "days.wednesday": "Quarta-feira",
    "days.thursday": "Quinta-feira",
    "days.friday": "Sexta-feira",
    "days.saturday": "Sábado",
    "days.sunday": "Domingo",
  },
  "en": {
    "settings.title": "Settings",
    "settings.subtitle": "Customize your workout",
    "settings.aiName": "Assistant name",
    "settings.calendar": "Calendar",
    "settings.tapToEdit": "Tap to edit",
    "settings.subscription": "Subscription",
    "settings.managePayment": "Manage plan and payment",
    "settings.manage": "Manage",
    "settings.theme": "Theme",
    "settings.changeAppearance": "Change appearance",
    "settings.language": "Language",
    "settings.selectLanguage": "Select language",
    "settings.termsOfUse": "Terms of Use",
    "settings.privacyPolicy": "Privacy Policy",
    "settings.support": "Support",
    "settings.logout": "Log out",
    "settings.logoutDesc": "Sign out of account",
    "settings.lightTheme": "Light theme enabled",
    "settings.darkTheme": "Dark theme enabled",
    "settings.languageUpdated": "Language updated!",
    "common.training": "Training",
    "common.rest": "Rest",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.back": "Back",
    "days.monday": "Monday",
    "days.tuesday": "Tuesday",
    "days.wednesday": "Wednesday",
    "days.thursday": "Thursday",
    "days.friday": "Friday",
    "days.saturday": "Saturday",
    "days.sunday": "Sunday",
  },
  "es": {
    "settings.title": "Configuración",
    "settings.subtitle": "Personaliza tu entrenamiento",
    "settings.aiName": "Nombre del asistente",
    "settings.calendar": "Calendario",
    "settings.tapToEdit": "Toca para editar",
    "settings.subscription": "Suscripción",
    "settings.managePayment": "Gestionar plan y pago",
    "settings.manage": "Gestionar",
    "settings.theme": "Tema",
    "settings.changeAppearance": "Cambiar apariencia",
    "settings.language": "Idioma",
    "settings.selectLanguage": "Selecciona el idioma",
    "settings.termsOfUse": "Términos de Uso",
    "settings.privacyPolicy": "Política de Privacidad",
    "settings.support": "Soporte",
    "settings.logout": "Cerrar sesión",
    "settings.logoutDesc": "Salir de la cuenta",
    "settings.lightTheme": "Tema claro activado",
    "settings.darkTheme": "Tema oscuro activado",
    "settings.languageUpdated": "¡Idioma actualizado!",
    "common.training": "Entrenamiento",
    "common.rest": "Descanso",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.back": "Volver",
    "days.monday": "Lunes",
    "days.tuesday": "Martes",
    "days.wednesday": "Miércoles",
    "days.thursday": "Jueves",
    "days.friday": "Viernes",
    "days.saturday": "Sábado",
    "days.sunday": "Domingo",
  },
  "fr": {
    "settings.title": "Paramètres",
    "settings.subtitle": "Personnalise ton entraînement",
    "settings.aiName": "Nom de l'assistant",
    "settings.calendar": "Calendrier",
    "settings.tapToEdit": "Appuie pour modifier",
    "settings.subscription": "Abonnement",
    "settings.managePayment": "Gérer le plan et le paiement",
    "settings.manage": "Gérer",
    "settings.theme": "Thème",
    "settings.changeAppearance": "Changer l'apparence",
    "settings.language": "Langue",
    "settings.selectLanguage": "Sélectionne la langue",
    "settings.termsOfUse": "Conditions d'utilisation",
    "settings.privacyPolicy": "Politique de confidentialité",
    "settings.support": "Support",
    "settings.logout": "Déconnexion",
    "settings.logoutDesc": "Se déconnecter du compte",
    "settings.lightTheme": "Thème clair activé",
    "settings.darkTheme": "Thème sombre activé",
    "settings.languageUpdated": "Langue mise à jour !",
    "common.training": "Entraînement",
    "common.rest": "Repos",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.back": "Retour",
    "days.monday": "Lundi",
    "days.tuesday": "Mardi",
    "days.wednesday": "Mercredi",
    "days.thursday": "Jeudi",
    "days.friday": "Vendredi",
    "days.saturday": "Samedi",
    "days.sunday": "Dimanche",
  },
  "de": {
    "settings.title": "Einstellungen",
    "settings.subtitle": "Passe dein Training an",
    "settings.aiName": "Assistentenname",
    "settings.calendar": "Kalender",
    "settings.tapToEdit": "Tippe zum Bearbeiten",
    "settings.subscription": "Abonnement",
    "settings.managePayment": "Plan und Zahlung verwalten",
    "settings.manage": "Verwalten",
    "settings.theme": "Theme",
    "settings.changeAppearance": "Aussehen ändern",
    "settings.language": "Sprache",
    "settings.selectLanguage": "Sprache auswählen",
    "settings.termsOfUse": "Nutzungsbedingungen",
    "settings.privacyPolicy": "Datenschutzrichtlinie",
    "settings.support": "Support",
    "settings.logout": "Abmelden",
    "settings.logoutDesc": "Vom Konto abmelden",
    "settings.lightTheme": "Helles Theme aktiviert",
    "settings.darkTheme": "Dunkles Theme aktiviert",
    "settings.languageUpdated": "Sprache aktualisiert!",
    "common.training": "Training",
    "common.rest": "Ruhe",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.back": "Zurück",
    "days.monday": "Montag",
    "days.tuesday": "Dienstag",
    "days.wednesday": "Mittwoch",
    "days.thursday": "Donnerstag",
    "days.friday": "Freitag",
    "days.saturday": "Samstag",
    "days.sunday": "Sonntag",
  },
  "it": {
    "settings.title": "Impostazioni",
    "settings.subtitle": "Personalizza il tuo allenamento",
    "settings.aiName": "Nome dell'assistente",
    "settings.calendar": "Calendario",
    "settings.tapToEdit": "Tocca per modificare",
    "settings.subscription": "Abbonamento",
    "settings.managePayment": "Gestisci piano e pagamento",
    "settings.manage": "Gestisci",
    "settings.theme": "Tema",
    "settings.changeAppearance": "Cambia aspetto",
    "settings.language": "Lingua",
    "settings.selectLanguage": "Seleziona la lingua",
    "settings.termsOfUse": "Termini di utilizzo",
    "settings.privacyPolicy": "Informativa sulla privacy",
    "settings.support": "Supporto",
    "settings.logout": "Disconnetti",
    "settings.logoutDesc": "Esci dall'account",
    "settings.lightTheme": "Tema chiaro attivato",
    "settings.darkTheme": "Tema scuro attivato",
    "settings.languageUpdated": "Lingua aggiornata!",
    "common.training": "Allenamento",
    "common.rest": "Riposo",
    "common.save": "Salva",
    "common.cancel": "Annulla",
    "common.back": "Indietro",
    "days.monday": "Lunedì",
    "days.tuesday": "Martedì",
    "days.wednesday": "Mercoledì",
    "days.thursday": "Giovedì",
    "days.friday": "Venerdì",
    "days.saturday": "Sabato",
    "days.sunday": "Domenica",
  },
  "nl": {
    "settings.title": "Instellingen",
    "settings.subtitle": "Pas je training aan",
    "settings.aiName": "Assistent naam",
    "settings.calendar": "Kalender",
    "settings.tapToEdit": "Tik om te bewerken",
    "settings.subscription": "Abonnement",
    "settings.managePayment": "Plan en betaling beheren",
    "settings.manage": "Beheren",
    "settings.theme": "Thema",
    "settings.changeAppearance": "Uiterlijk wijzigen",
    "settings.language": "Taal",
    "settings.selectLanguage": "Selecteer taal",
    "settings.termsOfUse": "Gebruiksvoorwaarden",
    "settings.privacyPolicy": "Privacybeleid",
    "settings.support": "Ondersteuning",
    "settings.logout": "Uitloggen",
    "settings.logoutDesc": "Afmelden van account",
    "settings.lightTheme": "Licht thema geactiveerd",
    "settings.darkTheme": "Donker thema geactiveerd",
    "settings.languageUpdated": "Taal bijgewerkt!",
    "common.training": "Training",
    "common.rest": "Rust",
    "common.save": "Opslaan",
    "common.cancel": "Annuleren",
    "common.back": "Terug",
    "days.monday": "Maandag",
    "days.tuesday": "Dinsdag",
    "days.wednesday": "Woensdag",
    "days.thursday": "Donderdag",
    "days.friday": "Vrijdag",
    "days.saturday": "Zaterdag",
    "days.sunday": "Zondag",
  },
  "ru": {
    "settings.title": "Настройки",
    "settings.subtitle": "Настрой свою тренировку",
    "settings.aiName": "Имя ассистента",
    "settings.calendar": "Календарь",
    "settings.tapToEdit": "Нажми для редактирования",
    "settings.subscription": "Подписка",
    "settings.managePayment": "Управление планом и оплатой",
    "settings.manage": "Управление",
    "settings.theme": "Тема",
    "settings.changeAppearance": "Изменить внешний вид",
    "settings.language": "Язык",
    "settings.selectLanguage": "Выбери язык",
    "settings.termsOfUse": "Условия использования",
    "settings.privacyPolicy": "Политика конфиденциальности",
    "settings.support": "Поддержка",
    "settings.logout": "Выйти",
    "settings.logoutDesc": "Выйти из аккаунта",
    "settings.lightTheme": "Светлая тема включена",
    "settings.darkTheme": "Тёмная тема включена",
    "settings.languageUpdated": "Язык обновлён!",
    "common.training": "Тренировка",
    "common.rest": "Отдых",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.back": "Назад",
    "days.monday": "Понедельник",
    "days.tuesday": "Вторник",
    "days.wednesday": "Среда",
    "days.thursday": "Четверг",
    "days.friday": "Пятница",
    "days.saturday": "Суббота",
    "days.sunday": "Воскресенье",
  },
  "zh": {
    "settings.title": "设置",
    "settings.subtitle": "定制你的训练",
    "settings.aiName": "助手名称",
    "settings.calendar": "日历",
    "settings.tapToEdit": "点击编辑",
    "settings.subscription": "订阅",
    "settings.managePayment": "管理计划和付款",
    "settings.manage": "管理",
    "settings.theme": "主题",
    "settings.changeAppearance": "更改外观",
    "settings.language": "语言",
    "settings.selectLanguage": "选择语言",
    "settings.termsOfUse": "使用条款",
    "settings.privacyPolicy": "隐私政策",
    "settings.support": "支持",
    "settings.logout": "退出登录",
    "settings.logoutDesc": "退出账户",
    "settings.lightTheme": "浅色主题已启用",
    "settings.darkTheme": "深色主题已启用",
    "settings.languageUpdated": "语言已更新！",
    "common.training": "训练",
    "common.rest": "休息",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.back": "返回",
    "days.monday": "星期一",
    "days.tuesday": "星期二",
    "days.wednesday": "星期三",
    "days.thursday": "星期四",
    "days.friday": "星期五",
    "days.saturday": "星期六",
    "days.sunday": "星期日",
  },
  "ja": {
    "settings.title": "設定",
    "settings.subtitle": "トレーニングをカスタマイズ",
    "settings.aiName": "アシスタント名",
    "settings.calendar": "カレンダー",
    "settings.tapToEdit": "タップして編集",
    "settings.subscription": "サブスクリプション",
    "settings.managePayment": "プランと支払いを管理",
    "settings.manage": "管理",
    "settings.theme": "テーマ",
    "settings.changeAppearance": "外観を変更",
    "settings.language": "言語",
    "settings.selectLanguage": "言語を選択",
    "settings.termsOfUse": "利用規約",
    "settings.privacyPolicy": "プライバシーポリシー",
    "settings.support": "サポート",
    "settings.logout": "ログアウト",
    "settings.logoutDesc": "アカウントからサインアウト",
    "settings.lightTheme": "ライトテーマが有効",
    "settings.darkTheme": "ダークテーマが有効",
    "settings.languageUpdated": "言語が更新されました！",
    "common.training": "トレーニング",
    "common.rest": "休息",
    "common.save": "保存",
    "common.cancel": "キャンセル",
    "common.back": "戻る",
    "days.monday": "月曜日",
    "days.tuesday": "火曜日",
    "days.wednesday": "水曜日",
    "days.thursday": "木曜日",
    "days.friday": "金曜日",
    "days.saturday": "土曜日",
    "days.sunday": "日曜日",
  },
  "ko": {
    "settings.title": "설정",
    "settings.subtitle": "운동을 맞춤 설정하세요",
    "settings.aiName": "어시스턴트 이름",
    "settings.calendar": "캘린더",
    "settings.tapToEdit": "탭하여 편집",
    "settings.subscription": "구독",
    "settings.managePayment": "플랜 및 결제 관리",
    "settings.manage": "관리",
    "settings.theme": "테마",
    "settings.changeAppearance": "외관 변경",
    "settings.language": "언어",
    "settings.selectLanguage": "언어 선택",
    "settings.termsOfUse": "이용약관",
    "settings.privacyPolicy": "개인정보 처리방침",
    "settings.support": "지원",
    "settings.logout": "로그아웃",
    "settings.logoutDesc": "계정에서 로그아웃",
    "settings.lightTheme": "라이트 테마 활성화됨",
    "settings.darkTheme": "다크 테마 활성화됨",
    "settings.languageUpdated": "언어가 업데이트되었습니다!",
    "common.training": "훈련",
    "common.rest": "휴식",
    "common.save": "저장",
    "common.cancel": "취소",
    "common.back": "뒤로",
    "days.monday": "월요일",
    "days.tuesday": "화요일",
    "days.wednesday": "수요일",
    "days.thursday": "목요일",
    "days.friday": "금요일",
    "days.saturday": "토요일",
    "days.sunday": "일요일",
  },
};

const getTranslations = (lang: Language): Record<string, string> => {
  return translations[lang] || translations["pt-PT"];
};

export { LanguageContext, getTranslations };
