// English translations - fixed language
const translations: Record<string, string> = {
  // Auth
  "auth.welcomeTo": "Welcome to",
  "auth.journeyStarts": "Your fitness journey starts here.",
  "auth.createAccount": "Create Account",
  "auth.login": "Log In",
  "auth.yourName": "Your name",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.noAccount": "Don't have an account?",
  "auth.hasAccount": "Already have an account?",
  "auth.signUp": "Sign Up",
  "auth.back": "Back",
  "auth.termsOfUse": "Terms of Use",
  "auth.privacyPolicy": "Privacy Policy",
  "auth.loginSuccess": "Login successful!",
  "auth.accountCreated": "Account created successfully!",
  "auth.emailRegistered": "This email is already registered. Try logging in.",
  "auth.invalidCredentials": "Invalid email or password.",
  
  // Home
  "home.rest": "Rest",
  "home.todayWorkout": "Today's workout",
  "home.recoveryDay": "Recovery day",
  "home.progress": "Progress",
  "home.seriesDone": "Sets done",
  "home.totalReps": "Total reps",
  "home.trainingMin": "Training min",
  "home.suggestedExercise": "Suggested exercise",
  "home.focusOn": "Focus on",
  "home.recovery": "Recovery",
  "home.upcomingWorkouts": "Upcoming workouts",
  "home.workoutComplete": "Workout complete! 💪",
  "home.congratsAllExercises": "Congrats, you completed all exercises today!",
  "home.exercises": "Exercises",
  "home.suggestedExercisesFor": "Suggested exercises for",
  "home.resetOnboarding": "Redo onboarding",
  "home.resetOnboardingDesc": "Reset your training preferences",
  "home.settings": "Settings",
  
  // Workout
  "workout.restDay": "Rest Day",
  "workout.activeRecovery": "Active Recovery",
  "workout.restImportant": "Rest is as important as training. Take time to recover!",
  "workout.trainingType": "Training Type",
  "workout.strength": "Strength",
  "workout.hypertrophy": "Hypertrophy",
  "workout.endurance": "Endurance",
  "workout.savedExercisesToday": "Exercises Saved Today",
  "workout.restCalculation": "Rest Calculation",
  "workout.baseTime": "Base time",
  "workout.weight": "Weight",
  "workout.reps": "Reps",
  "workout.highSets": "High sets",
  "workout.totalRecommended": "Total recommended",
  "workout.restTimer": "Timer",
  "workout.restEnded": "Rest time ended! 💪",
  "workout.selectExercise": "Select an exercise first",
  "workout.saved": "saved!",
  
  // Nutrition
  "nutrition.title": "Nutrition",
  "nutrition.mealsToday": "Today's Meals",
  "nutrition.noMeals": "You haven't logged any meals yet",
  "nutrition.useScannerHint": "Use the AI scanner above to get started!",
  "nutrition.protein": "Protein",
  "nutrition.carbs": "Carbs",
  "nutrition.fat": "Fat",
  "nutrition.plansRecipes": "Plans & Recipes",
  "nutrition.tipsForAthletes": "Tips for Athletes",
  "nutrition.postWorkout": "Post-workout",
  "nutrition.postWorkoutTip": "Protein + carbs within 2h after training",
  "nutrition.distributedProtein": "Distributed protein",
  "nutrition.distributedProteinTip": "20-40g per meal is ideal",
  
  // Chat
  "chat.hello": "Hello! I'm",
  "chat.askMe": "Ask me about workouts, nutrition, recovery, or your progress!",
  "chat.suggestWorkout": "Suggest workout",
  "chat.recovery": "Recovery",
  "chat.substitute": "Substitute",
  "chat.progressLabel": "Progress",
  "chat.nutritionLabel": "Nutrition",
  "chat.restLabel": "Rest",
  "chat.continuousMode": "Continuous conversation",
  "chat.continuousModeOn": "Continuous mode enabled",
  "chat.continuousModeOff": "Continuous mode disabled",
  "chat.listen": "Listen",
  "chat.playing": "Playing...",
  "chat.recording": "Recording...",
  "chat.transcribing": "Transcribing...",
  "chat.placeholder": "Type a message...",
  "chat.tapToCancel": "Tap to cancel",
  "chat.errorCreatingConversation": "Error creating conversation. Log in to save history.",
  "chat.errorAI": "Error communicating with AI. Please try again.",
  "chat.limitExceeded": "Request limit exceeded. Try again in a few seconds.",
  "chat.creditsExhausted": "Credits exhausted. Add more credits in settings.",
  
  // Alerts
  "alerts.title": "Alerts",
  "alerts.subtitle": "Your training assistant",
  "alerts.workoutRecorded": "Workout recorded! 💪",
  "alerts.streakMilestone": "Streak Milestone!",
  "alerts.consecutiveDays": "consecutive training days!",
  
  // Settings
  "settings.title": "Settings",
  "settings.subtitle": "Customize your training",
  "settings.aiName": "Assistant name",
  "settings.calendar": "Calendar",
  "settings.tapToEdit": "Tap to edit",
  "settings.subscription": "Subscription",
  "settings.managePayment": "Manage plan and payment",
  "settings.manage": "Manage",
  "settings.theme": "Theme",
  "settings.changeAppearance": "Change appearance",
  "settings.language": "Language",
  "settings.selectLanguage": "Select language",
  "settings.termsOfUse": "Terms of Use",
  "settings.privacyPolicy": "Privacy Policy",
  "settings.support": "Support",
  "settings.logout": "Log out",
  "settings.logoutDesc": "Sign out of your account",
  "settings.lightTheme": "Light theme enabled",
  "settings.darkTheme": "Dark theme enabled",
  "settings.languageUpdated": "Language updated!",
  "settings.aiNameUpdated": "AI name updated!",
  "settings.errorPortal": "Error opening management portal",
  "settings.sessionEnded": "Session ended",
  "settings.errorLogout": "Error logging out",
  
  // BottomNav
  "nav.home": "Home",
  "nav.workout": "Workout",
  "nav.nutrition": "Nutrition",
  "nav.chat": "Chat",
  "nav.alerts": "Alerts",
  
  // Common
  "common.training": "Training",
  "common.rest": "Rest",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.back": "Back",
  "common.loading": "Loading...",
  "common.error": "Error",
  "common.success": "Success",
  "common.incredible": "Incredible!",
  
  // Days
  "days.sunday": "Sunday",
  "days.monday": "Monday",
  "days.tuesday": "Tuesday",
  "days.wednesday": "Wednesday",
  "days.thursday": "Thursday",
  "days.friday": "Friday",
  "days.saturday": "Saturday",
  "days.sun": "Sun",
  "days.mon": "Mon",
  "days.tue": "Tue",
  "days.wed": "Wed",
  "days.thu": "Thu",
  "days.fri": "Fri",
  "days.sat": "Sat",
  
  // AI Workout Generator
  "aiWorkout.title": "AI Workout Generator",
  "aiWorkout.generating": "Generating personalized workout...",
  "aiWorkout.generateFor": "Generate Workout for",
  "aiWorkout.noMuscleGroups": "No muscle groups defined for today",
  "aiWorkout.success": "Workout generated successfully! 💪",
  "aiWorkout.error": "Error generating workout. Please try again.",
  "aiWorkout.progress": "Progress",
  "aiWorkout.exercises": "exercises",
  "aiWorkout.duration": "Duration",
  "aiWorkout.level": "Level",
  "aiWorkout.warmup": "Warm-up",
  "aiWorkout.cooldown": "Cool-down",
  "aiWorkout.tip": "Tip",
  "aiWorkout.equipment": "Equipment",
  "aiWorkout.useInRecord": "Use in record →",
  "aiWorkout.regenerate": "Generate New Workout",
  "aiWorkout.rest": "rest",
  
  // Food Scanner
  "foodScanner.addMeal": "Add Meal",
  "foodScanner.takePhoto": "Take Photo",
  "foodScanner.gallery": "Gallery",
  "foodScanner.orDescribe": "or describe",
  "foodScanner.exampleDescription": "E.g., 200g grilled chicken, brown rice...",
  "foodScanner.analyzing": "Analyzing with AI...",
  "foodScanner.analysisComplete": "Analysis complete!",
  "foodScanner.foodsIdentified": "food(s) identified",
  "foodScanner.analysisError": "Analysis error",
  "foodScanner.analysisErrorDesc": "Could not analyze the image. Please try again.",
  "foodScanner.textAnalysisError": "Could not analyze the description.",
  "foodScanner.addedFood": "added",
  "foodScanner.mealAdded": "Meal added!",
  "foodScanner.kcalRegistered": "kcal registered",
  "foodScanner.identifiedFoods": "Identified foods",
  "foodScanner.total": "Total",
  "foodScanner.protein": "Protein",
  "foodScanner.carbs": "Carbs",
  "foodScanner.fat": "Fat",
  "foodScanner.fiber": "Fiber",
  "foodScanner.aiScanner": "AI Scanner",
  "foodScanner.search": "Search",
  "foodScanner.searchFoods": "Search foods...",
  "foodScanner.suggestions": "Suggestions",
  "foodScanner.postWorkoutSuggestions": "Post-Workout",
  "foodScanner.preWorkoutSuggestions": "Pre-Workout",
  "foodScanner.results": "Results",
  "foodScanner.noFoodFound": "No food found",
  "foodScanner.selected": "Selected",
  "foodScanner.items": "items",
  "foodScanner.newAnalysis": "New Analysis",
  "foodScanner.clear": "Clear",
  "foodScanner.add": "Add",
  "foodScanner.postWorkoutWindow": "Post-Workout Window",
  "foodScanner.preWorkoutPrep": "Pre-Workout Prep",
  "foodScanner.activeRecovery": "Active Recovery",
  
  // Hydration Card
  "hydration.title": "Hydration",
  "hydration.every": "Every",
  "hydration.min": "min",
  "hydration.configure": "Configure Hydration",
  "hydration.enableReminders": "Enable reminders",
  "hydration.interval": "Interval",
  "hydration.dailyGoal": "Daily goal",
  "hydration.remove": "Remove",
  
  // Streak Card
  "streak.title": "Consistency",
  "streak.recordedToday": "Workout recorded today! 💪",
  "streak.startNew": "Start a new streak!",
  "streak.legendary": "Legendary! Keep it up!",
  "streak.unstoppable": "Unstoppable! 2 weeks!",
  "streak.oneWeek": "One week! Excellent!",
  "streak.dontBreak": "Don't break the streak!",
  "streak.recordWorkout": "Record Workout",
  "streak.days": "DAYS",
  "streak.record": "Record",
  "streak.daysLabel": "days",
  "streak.total": "Total",
  "streak.workouts": "workouts",
  
  // Supplements Card
  "supplements.title": "Supplements",
  "supplements.activeReminders": "active reminders",
  "supplements.newSupplement": "New Supplement",
  "supplements.name": "Name",
  "supplements.namePlaceholder": "E.g., Omega 3, BCAA...",
  "supplements.time": "Time",
  "supplements.addSupplement": "Add Supplement",
  "supplements.noSupplements": "No supplements configured",
  
  // Sleep Card
  "sleep.title": "Sleep & Recovery",
  "sleep.reminderBefore": "Reminder",
  "sleep.minBefore": "min before",
  "sleep.configure": "Configure Sleep",
  "sleep.enableReminders": "Enable reminders",
  "sleep.sleep": "Sleep",
  "sleep.wake": "Wake",
  "sleep.reminderBeforeLabel": "Reminder before",
  "sleep.excellent": "Excellent",
  "sleep.good": "Good",
  "sleep.fair": "Fair",
  "sleep.insufficient": "Insufficient",
  "sleep.sleepEqualsGains": "Sleep = Gains",
  "sleep.recoversMusles": "Recovers muscles",
  
  // Quick Timer Card
  "timer.title": "Quick Timer",
  "timer.restBetweenSets": "Rest between sets",
  "timer.remaining": "remaining",
  "timer.stop": "Stop",
  "timer.restart": "Restart",
  
  // Meal Notification Card
  "mealNotification.title": "Meal Reminders",
  "mealNotification.enableNotificationsFirst": "Enable notifications first",
  "mealNotification.mealsActive": "meals active",
  "mealNotification.disabled": "Disabled",
  "mealNotification.mealTimes": "Meal Times",
  "mealNotification.breakfast": "Breakfast",
  "mealNotification.morningSnack": "Morning Snack",
  "mealNotification.lunch": "Lunch",
  "mealNotification.afternoonSnack": "Afternoon Snack",
  "mealNotification.dinner": "Dinner",
  "mealNotification.preWorkout": "Pre-Workout",
  "mealNotification.postWorkout": "Post-Workout",
  "mealNotification.waterReminders": "Water Reminders",
  "mealNotification.hydrationThroughDay": "Hydration throughout the day",
  "mealNotification.start": "Start",
  "mealNotification.end": "End",
  "mealNotification.intervalHours": "Interval (hours)",
  
  // Workout Reminder Card
  "workoutReminder.title": "Workout Reminder",
  "workoutReminder.minBeforeWorkout": "min before workout",
  "workoutReminder.configure": "Configure Reminder",
  "workoutReminder.enableReminders": "Enable reminders",
  "workoutReminder.workoutTime": "Workout time",
  "workoutReminder.notifyBefore": "Notify before",
  "workoutReminder.motivationalMessage": "Motivational message",
  "workoutReminder.enableNotificationsFirst": "Enable notifications first to use reminders",
  "workoutReminder.timeToTrain": "Time to Train!",
  "workoutReminder.now": "now",
  "workoutReminder.notificationPreview": "Notification preview",
};

export const useLanguage = () => {
  const t = (key: string): string => {
    return translations[key] || key;
  };

  return { t };
};
